In [1]:
%%sh
# current_path=$(pwd)
# parent_dir=$(dirname "$current_dir")
export PROJECT_HOME="/home/ivan/Uforse/university_crawl"
echo $PROJECT_HOME
if [ -f "${PROJECT_HOME}/build" ]; then
    echo "Found build in PROJECT_HOME. Sourcing now..."
    . "${PROJECT_HOME}/build"
    echo "build executed successfully."
else
    echo "Error: build not found in PROJECT_HOME."
fi

/home/ivan/Uforse/university_crawl
Found build in PROJECT_HOME. Sourcing now...
Obtaining file:///home/ivan/Uforse/university_crawl/university_info_generator
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pandas in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.4) (2.2.2)
Requirement already satisfied: numpy in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.4) (1.26.4)
Requirement already satisfied: gspread in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.4) (6.1.0)
Requirement already satisfied: oauth2client in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.4) (4.1.3)
Requirement already satisfied: openai in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.4) (1.37.2)
Requirement already satisfied: python-dotenv in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.4) (0.21.0)
Requirement already satisfied: gspread_dataframe in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.4) (3.3.1)
Requirement already satisfied: bs4 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.4) (0.0.2)
Requirement already satisfied: tenacity in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.4) (8.2.3)
Requirement already satisfied: langchain in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.4) (0.1.16)
Requirement already satisfied: langchain-openai in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.4) (0.1.3)
Requirement already satisfied: google-api-python-client in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.4) (2.127.0)
Requirement already satisfied: langchain-chroma in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.4) (0.1.0)
Requirement already satisfied: tavily-python in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.4) (0.3.3)
Requirement already satisfied: selenium in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.4) (4.21.0)
Requirement already satisfied: beautifulsoup4 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from bs4->university-info-generator==0.0.4) (4.11.1)
Requirement already satisfied: httplib2<1.dev0,>=0.19.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-python-client->university-info-generator==0.0.4) (0.22.0)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-python-client->university-info-generator==0.0.4) (2.27.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-python-client->university-info-generator==0.0.4) (0.2.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-python-client->university-info-generator==0.0.4) (2.18.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-python-client->university-info-generator==0.0.4) (4.1.1)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from gspread->university-info-generator==0.0.4) (1.2.0)
Requirement already satisfied: StrEnum==0.4.15 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from gspread->university-info-generator==0.0.4) (0.4.15)
Requirement already satisfied: six>=1.12.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from gspread_dataframe->university-info-generator==0.0.4) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from pandas->university-info-generator==0.0.4) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from pandas->university-info-generator==0.0.4) (2022.7)
Requirement already satisfied: tzdata>=2022.7 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from pandas->university-info-generator==0.0.4) (2024.1)
Requirement already satisfied: PyYAML>=5.3 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.4) (6.0)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.4) (2.0.29)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.4) (3.8.3)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.4) (4.0.2)
Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.4) (0.6.4)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.4) (1.33)
Requirement already satisfied: langchain-community<0.1,>=0.0.32 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.4) (0.0.36)
Requirement already satisfied: langchain-core<0.2.0,>=0.1.42 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.4) (0.1.48)
Requirement already satisfied: langchain-text-splitters<0.1,>=0.0.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.4) (0.0.1)
Requirement already satisfied: langsmith<0.2.0,>=0.1.17 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.4) (0.1.50)
Requirement already satisfied: pydantic<3,>=1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.4) (1.10.11)
Requirement already satisfied: requests<3,>=2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.4) (2.28.1)
Requirement already satisfied: chromadb<0.5.0,>=0.4.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain-chroma->university-info-generator==0.0.4) (0.4.24)
Requirement already satisfied: fastapi<1,>=0.95.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain-chroma->university-info-generator==0.0.4) (0.110.2)
Requirement already satisfied: tiktoken<1,>=0.5.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain-openai->university-info-generator==0.0.4) (0.6.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from openai->university-info-generator==0.0.4) (3.5.0)
Requirement already satisfied: distro<2,>=1.7.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from openai->university-info-generator==0.0.4) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from openai->university-info-generator==0.0.4) (0.27.0)
Requirement already satisfied: sniffio in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from openai->university-info-generator==0.0.4) (1.2.0)
Requirement already satisfied: tqdm>4 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from openai->university-info-generator==0.0.4) (4.66.2)
Requirement already satisfied: typing-extensions<5,>=4.7 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from openai->university-info-generator==0.0.4) (4.11.0)
Requirement already satisfied: pyasn1>=0.1.7 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from oauth2client->university-info-generator==0.0.4) (0.4.8)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from oauth2client->university-info-generator==0.0.4) (0.2.8)
Requirement already satisfied: rsa>=3.1.4 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from oauth2client->university-info-generator==0.0.4) (4.9)
Requirement already satisfied: urllib3<3,>=1.26 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from urllib3[socks]<3,>=1.26->selenium->university-info-generator==0.0.4) (1.26.14)
Requirement already satisfied: trio~=0.17 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from selenium->university-info-generator==0.0.4) (0.22.2)
Requirement already satisfied: trio-websocket~=0.9 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from selenium->university-info-generator==0.0.4) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from selenium->university-info-generator==0.0.4) (2023.7.22)
Requirement already satisfied: attrs>=17.3.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->university-info-generator==0.0.4) (22.1.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->university-info-generator==0.0.4) (2.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->university-info-generator==0.0.4) (6.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->university-info-generator==0.0.4) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->university-info-generator==0.0.4) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->university-info-generator==0.0.4) (1.2.0)
Requirement already satisfied: idna>=2.8 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from anyio<5,>=3.5.0->openai->university-info-generator==0.0.4) (2.10)
Requirement already satisfied: build>=1.0.3 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (1.2.1)
Requirement already satisfied: chroma-hnswlib==0.7.3 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (0.7.3)
Requirement already satisfied: uvicorn>=0.18.3 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from uvicorn[standard]>=0.18.3->chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (0.29.0)
Requirement already satisfied: posthog>=2.4.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (3.5.0)
Requirement already satisfied: pulsar-client>=3.1.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (3.5.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (1.17.3)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (1.24.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (1.24.0)
Requirement already satisfied: opentelemetry-instrumentation-fastapi>=0.41b0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (0.45b0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (1.24.0)
Requirement already satisfied: tokenizers>=0.13.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (0.19.1)
Requirement already satisfied: pypika>=0.48.9 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (0.48.9)
Requirement already satisfied: overrides>=7.3.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (7.7.0)
Requirement already satisfied: importlib-resources in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (6.4.0)
Requirement already satisfied: grpcio>=1.58.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (1.62.2)
Requirement already satisfied: bcrypt>=4.0.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (4.1.2)
Requirement already satisfied: typer>=0.9.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (0.12.3)
Requirement already satisfied: kubernetes>=28.1.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (29.0.0)
Requirement already satisfied: mmh3>=4.0.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (4.1.0)
Requirement already satisfied: orjson>=3.9.12 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (3.10.1)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain->university-info-generator==0.0.4) (3.21.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain->university-info-generator==0.0.4) (0.8.0)
Requirement already satisfied: starlette<0.38.0,>=0.37.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from fastapi<1,>=0.95.2->langchain-chroma->university-info-generator==0.0.4) (0.37.2)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client->university-info-generator==0.0.4) (1.63.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client->university-info-generator==0.0.4) (4.21.12)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client->university-info-generator==0.0.4) (1.23.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client->university-info-generator==0.0.4) (5.3.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-auth-oauthlib>=0.4.1->gspread->university-info-generator==0.0.4) (1.3.1)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from httplib2<1.dev0,>=0.19.0->google-api-python-client->university-info-generator==0.0.4) (3.0.9)
Requirement already satisfied: httpcore==1.* in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from httpx<1,>=0.23.0->openai->university-info-generator==0.0.4) (1.0.5)
Requirement already satisfied: h11<0.15,>=0.13 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai->university-info-generator==0.0.4) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from jsonpatch<2.0,>=1.33->langchain->university-info-generator==0.0.4) (2.4)
Requirement already satisfied: packaging<24.0,>=23.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain-core<0.2.0,>=0.1.42->langchain->university-info-generator==0.0.4) (23.2)
Requirement already satisfied: greenlet!=0.4.17 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from SQLAlchemy<3,>=1.4->langchain->university-info-generator==0.0.4) (3.0.3)
Requirement already satisfied: regex>=2022.1.18 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from tiktoken<1,>=0.5.2->langchain-openai->university-info-generator==0.0.4) (2022.7.9)
Requirement already satisfied: sortedcontainers in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from trio~=0.17->selenium->university-info-generator==0.0.4) (2.4.0)
Requirement already satisfied: outcome in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from trio~=0.17->selenium->university-info-generator==0.0.4) (1.2.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from trio~=0.17->selenium->university-info-generator==0.0.4) (1.1.3)
Requirement already satisfied: wsproto>=0.14 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from trio-websocket~=0.9->selenium->university-info-generator==0.0.4) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from urllib3[socks]<3,>=1.26->selenium->university-info-generator==0.0.4) (1.7.1)
Requirement already satisfied: soupsieve>1.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from beautifulsoup4->bs4->university-info-generator==0.0.4) (2.3.2.post1)
Requirement already satisfied: pyproject_hooks in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from build>=1.0.3->chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (1.0.0)
Requirement already satisfied: importlib-metadata>=4.6 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from build>=1.0.3->chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.4) (7.0.0)

  DEPRECATION: Legacy editable install of university-info-generator==0.0.4 from file:///home/ivan/Uforse/university_crawl/university_info_generator (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457

In [2]:
import os
import sys
from pprint import pprint

#'/home/ivan/Uforse/university_crawl/fetch_logic'
current_path = os.path.abspath('./')

#'/home/ivan/Uforse/university_crawl'
parent_path = os.path.dirname(current_path)
sys.path.append(parent_path)
import sys
print(sys.executable)
sys.path.append('/home/ivan/Uforse/university_crawl')

/home/ivan/anaconda3/envs/gpu/bin/python

In [3]:
usa_universities = [
    "Princeton University",
    "Massachusetts Institute of Technology",
    "Harvard University",
    "Stanford University",
    "Yale University",
    "University of Pennsylvania",
    "California Institute of Technology",
    "Duke University",
    "Brown University",
    "Johns Hopkins University",
    "Northwestern University",
    "Columbia University",
    "Cornell University",
    "University of Chicago",
    "University of California, Berkeley",
    "University of California, Los Angeles",
    "Rice University",
    "Dartmouth College",
    "Vanderbilt University",
    "University of Notre Dame",
    "University of Michigan",
    "Georgetown University",
    "University of North Carolina at Chapel Hill",
    "Carnegie Mellon University",
    "Emory University",
    "University of Virginia",
    "Washington University in St. Louis",
    "University of California, Davis",
    "University of California, San Diego",
    "University of Florida",
    "University of Southern California",
    "University of Texas at Austin",
    "Georgia Institute of Technology",
    "University of California, Irvine",
    "New York University",
    "University of California, Santa Barbara",
    "University of Illinois Urbana-Champaign",
    "University of Wisconsin-Madison",
    "Boston College",
    "Rutgers University-New Brunswick",
    "Tufts University",
    "University of Washington",
    "Boston University",
    "Ohio State University",
    "Purdue University",
    "University of Maryland, College Park",
    "Lehigh University",
    "Texas A&M University",
    "University of Georgia",
    "University of Rochester"
]

In [4]:
from university_info_generator import config
from university_info_generator import UniversityInfoGenerator
from university_info_generator import UniversityBasicInfoType, UniversitySavedDictType, GPTMethodType, HandlerType
from university_info_generator.utility.google_sheet_utility import *
from university_info_generator.utility.save_load_utility import *
from university_info_generator.configs import ALL_ATTRIBUTE_NAME

In [5]:
print(ALL_ATTRIBUTE_NAME)

[0, 'university_name', 'abbreviation', 'website', 'wikipedia', 'id_', 'university_type', 'graduation_year', 'location', 'graduation_rate', 'domestic_student_tuition', 'international_student_tuition', 'description', 'ranking_qs_news_2024', 'ranking_us_news_2023', 'ranking_times_rank_2024', 'ranking_arwu_rank_2023', 'website', 'important_calendar', 'statistics', 'faculty', 'popular_programs', 'programs', 'characteristics', 'wikipedia', 'others', 'mission', 'vision', 'values', 'admission_rate']

In [6]:
# attr_df = get_attribute_df()
# attr_df.head(26)
# attr_dict = attr_df.to_dict(orient='records')
# store_cache("./attr.jsonl", get_attribute_dict())

In [7]:
uni_gen = UniversityInfoGenerator()
uni_gen.load_from_file(UniversitySavedDictType.ATTRIBUTE, "./attr.jsonl")
uni_gen.load_from_file(UniversitySavedDictType.GPT_CACHE, "./gpt_cache_usa.jsonl")
uni_gen.load_from_file(UniversitySavedDictType.UNIVERSITY_BASIC_INFO, "./university_basic_info_usa.jsonl")
# uni_gen.load_from_file(UniversitySavedDictType.UNIVERSITY_INFO, "./university_info_usa.jsonl")

In [8]:
for uni_name, id_ in zip(usa_universities, range(2001, 2051)):
    print(uni_name, id_)
    uni_gen.get_university_basic_info(uni_name, id_, param_type = UniversityBasicInfoType.UNIVERSITY_NAME)

Princeton University 2001
Massachusetts Institute of Technology 2002
Harvard University 2003
Stanford University 2004
Yale University 2005
University of Pennsylvania 2006
California Institute of Technology 2007
Duke University 2008
Brown University 2009
Johns Hopkins University 2010
Northwestern University 2011
Columbia University 2012
Cornell University 2013
University of Chicago 2014
University of California, Berkeley 2015
University of California, Los Angeles 2016
Rice University 2017
Dartmouth College 2018
Vanderbilt University 2019
University of Notre Dame 2020
University of Michigan 2021
Georgetown University 2022
University of North Carolina at Chapel Hill 2023
Carnegie Mellon University 2024
Emory University 2025
University of Virginia 2026
Washington University in St. Louis 2027
University of California, Davis 2028
University of California, San Diego 2029
University of Florida 2030
University of Southern California 2031
University of Texas at Austin 2032
Georgia Institute of Technology 2033
University of California, Irvine 2034
New York University 2035
University of California, Santa Barbara 2036
University of Illinois Urbana-Champaign 2037
University of Wisconsin-Madison 2038
Boston College 2039
Rutgers University-New Brunswick 2040
Tufts University 2041
University of Washington 2042
Boston University 2043
Ohio State University 2044
Purdue University 2045
University of Maryland, College Park 2046
Lehigh University 2047
Texas A&M University 2048
University of Georgia 2049
University of Rochester 2050

In [9]:
uni_gen.save_to_file(UniversitySavedDictType.UNIVERSITY_BASIC_INFO, "./university_basic_info_usa.jsonl")

In [10]:
from typing import Any
result_dict:Dict[str, Dict[str, Any]] = {}
for k in uni_gen.university_info_dict:
    value = uni_gen.university_info_dict[k]
    if type(value) == dict:
        result_dict[k] = value
    elif type(value) == University:
        result_dict[k] = value.to_dict_en()
file_path = "./fetch_data/all_universities_usa_info.csv"

In [20]:
for uni_name, id_ in zip(usa_universities, range(2001, 2051)):
    # print(uni_name, id_)
    uni_gen.get_university_info(uni_name, id_)
    # uni_gen.get_info_by_attribute(uni_name, attribute_name="mission")
    # uni_gen.get_info_by_attribute(uni_name, attribute_name="vision")
    # uni_gen.get_info_by_attribute(uni_name, attribute_name="values")
    # uni_gen.get_info_by_attribute(uni_name, attribute_name="admission_rate")
    
    # break

used langchain: get_retrieved_attr_with_format_tavily, university_name: Massachusetts Institute of Technology,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: Massachusetts Institute of Technology,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Massachusetts Institute of Technology,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Massachusetts Institute of Technology,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Massachusetts Institute of Technology,                     attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Massachusetts Institute of Technology,                     attribute: mission
used GPT: get_value_and_reference_from_gpt, university_name: Massachusetts Institute of Technology,                     attribute: vision
used GPT: get_value_and_reference_from_gpt, university_name: Massachusetts Institute of Technology,                     attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Harvard University,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: Harvard University,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Harvard University,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Harvard University,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Harvard University,                     attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Harvard University,                     attribute: mission
used GPT: get_value_and_reference_from_gpt, university_name: Harvard University,                     attribute: vision
used GPT: get_value_and_reference_from_gpt, university_name: Harvard University,                     attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Stanford University,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: Stanford University,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Stanford University,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Stanford University,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Stanford University,                     attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Stanford University,                     attribute: mission
used GPT: get_value_and_reference_from_gpt, university_name: Stanford University,                     attribute: values
used GPT: get_value_and_reference_from_gpt, university_name: Stanford University,                     attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Yale University,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: Yale University,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Yale University,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Yale University,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Yale University,                     attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Yale University,                     attribute: mission
used GPT: get_value_and_reference_from_gpt, university_name: Yale University,                     attribute: vision
used GPT: get_value_and_reference_from_gpt, university_name: Yale University,                     attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Pennsylvania,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Pennsylvania,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Pennsylvania,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Pennsylvania,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: University of Pennsylvania,                     attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: University of Pennsylvania,                     attribute: vision
used GPT: get_value_and_reference_from_gpt, university_name: University of Pennsylvania,                     attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: California Institute of Technology,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: California Institute of Technology,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: California Institute of Technology,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: California Institute of Technology,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: California Institute of Technology,                     attribute: values
used GPT: get_value_and_reference_from_gpt, university_name: California Institute of Technology,                     attribute: mission
used GPT: get_value_and_reference_from_gpt, university_name: California Institute of Technology,                     attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Duke University,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: Duke University,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Duke University,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Duke University,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Duke University,                     attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Duke University,                     attribute: vision
used GPT: get_value_and_reference_from_gpt, university_name: Duke University,                     attribute: mission
used GPT: get_value_and_reference_from_gpt, university_name: Duke University,                     attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Brown University,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: Brown University,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Brown University,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Brown University,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Brown University,                     attribute: mission
used GPT: get_value_and_reference_from_gpt, university_name: Brown University,                     attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Brown University,                     attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Johns Hopkins University,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: Johns Hopkins University,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Johns Hopkins University,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Johns Hopkins University,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Johns Hopkins University,                     attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Johns Hopkins University,                     attribute: values
used GPT: get_value_and_reference_from_gpt, university_name: Johns Hopkins University,                     attribute: mission
used GPT: get_value_and_reference_from_gpt, university_name: Johns Hopkins University,                     attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Northwestern University,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: Northwestern University,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Northwestern University,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Northwestern University,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Northwestern University,                     attribute: mission
used GPT: get_value_and_reference_from_gpt, university_name: Northwestern University,                     attribute: vision
used GPT: get_value_and_reference_from_gpt, university_name: Northwestern University,                     attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Northwestern University,                     attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Columbia University,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: Columbia University,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Columbia University,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Columbia University,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Columbia University,                     attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Columbia University,                     attribute: vision
Failed to decode JSON from the response.
used GPT: get_value_and_reference_from_gpt, university_name: Columbia University,                     attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: Cornell University,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: Cornell University,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Cornell University,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Cornell University,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Cornell University,                     attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Cornell University,                     attribute: vision
used GPT: get_value_and_reference_from_gpt, university_name: Cornell University,                     attribute: values
used GPT: get_value_and_reference_from_gpt, university_name: Cornell University,                     attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Chicago,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Chicago,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Chicago,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Chicago,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: University of Chicago,                     attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: University of Chicago,                     attribute: vision
used GPT: get_value_and_reference_from_gpt, university_name: University of Chicago,                     attribute: mission
used GPT: get_value_and_reference_from_gpt, university_name: University of Chicago,                     attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of California, Berkeley,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of California, Berkeley,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of California, Berkeley,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of California, Berkeley,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: University of California, Berkeley,                     attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: University of California, Berkeley,                     attribute: mission
used GPT: get_value_and_reference_from_gpt, university_name: University of California, Berkeley,                     attribute: vision
used GPT: get_value_and_reference_from_gpt, university_name: University of California, Berkeley,                     attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of California, Los Angeles,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of California, Los Angeles,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of California, Los Angeles,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of California, Los Angeles,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: University of California, Los Angeles,                     attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: University of California, Los Angeles,                     attribute: vision
Failed to decode JSON from the response.
used GPT: get_value_and_reference_from_gpt, university_name: University of California, Los Angeles,                     attribute: mission
used GPT: get_value_and_reference_from_gpt, university_name: University of California, Los Angeles,                     attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Rice University,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: Rice University,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Rice University,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Rice University,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Rice University,                     attribute: values
used GPT: get_value_and_reference_from_gpt, university_name: Rice University,                     attribute: mission
Failed to decode JSON from the response.
used GPT: get_value_and_reference_from_gpt, university_name: Rice University,                     attribute: vision
used GPT: get_value_and_reference_from_gpt, university_name: Rice University,                     attribute: admission_rate
used langchain: get_retrieved_attr_with_format_tavily, university_name: Dartmouth College,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: Dartmouth College,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Dartmouth College,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Dartmouth College,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Dartmouth College,                     attribute: vision
used GPT: get_value_and_reference_from_gpt, university_name: Dartmouth College,                     attribute: values
used GPT: get_value_and_reference_from_gpt, university_name: Dartmouth College,                     attribute: mission
used GPT: get_value_and_reference_from_gpt, university_name: Dartmouth College,                     attribute: admission_rate
used langchain: get_retrieved_attr_with_format_tavily, university_name: Vanderbilt University,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: Vanderbilt University,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: Vanderbilt University,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: Vanderbilt University,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: Vanderbilt University,                     attribute: values
used GPT: get_value_and_reference_from_gpt, university_name: Vanderbilt University,                     attribute: vision
Failed to decode JSON from the response.
used GPT: get_value_and_reference_from_gpt, university_name: Vanderbilt University,                     attribute: mission
used GPT: get_value_and_reference_from_gpt, university_name: Vanderbilt University,                     attribute: admission_rate
Failed to decode JSON from the response.
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Notre Dame,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Notre Dame,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Notre Dame,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Notre Dame,
                attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: University of Notre Dame,                     attribute: admission_rate
used GPT: get_value_and_reference_from_gpt, university_name: University of Notre Dame,                     attribute: mission
used GPT: get_value_and_reference_from_gpt, university_name: University of Notre Dame,                     attribute: vision
used GPT: get_value_and_reference_from_gpt, university_name: University of Notre Dame,                     attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Michigan,
                attribute: mission
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Michigan,
                attribute: vision
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Michigan,
                attribute: values
used langchain: get_retrieved_attr_with_format_tavily, university_name: University of Michigan,
                attribute: admission_rate

In [21]:
uni_gen.save_to_file(UniversitySavedDictType.UNIVERSITY_INFO, "./university_info_usa.jsonl")
# break
print("here")

here

In [22]:
from typing import Any
result_dict:Dict[str, Dict[str, Any]] = {}
for k in uni_gen.university_info_dict:
    value = uni_gen.university_info_dict[k]
    if type(value) == dict:
        result_dict[k] = value
    elif type(value) == University:
        result_dict[k] = value.to_dict_en()
file_path = "./all_universities_usa_info.csv"

In [23]:
df = pd.DataFrame.from_dict(result_dict, orient="index").reset_index()
df.head()
df.to_csv("./all_universities_usa_info.csv", index=False)
df.to_csv(file_path, index=False, encoding="utf-8")

In [24]:
df.head()

,index,id_,university_name,abbreviation,website,wikipedia,university_type,graduation_year,location,graduation_rate,...,statistics,faculty,popular_programs,programs,characteristics,others,mission,vision,admission_rate,values
0,Princeton University,2001,Princeton University,,,,,,,,...,,,,,,,Princeton University advances learning through...,Princeton University aims to be a world leader...,0.043,Princeton University upholds several core valu...
1,Massachusetts Institute of Technology,2002,Massachusetts Institute of Technology,,,,,,,,...,,,,,,,The mission of the Massachusetts Institute of ...,The mission of MIT is to advance knowledge and...,0.143,The Massachusetts Institute of Technology (MIT...
2,Harvard University,2003,Harvard University,,,,,,,,...,,,,,,,The mission of Harvard University is to educat...,Harvard University aims to educate the citizen...,0.039,Harvard University upholds several core values...
3,Stanford University,2004,Stanford University,,,,,,,,...,,,,,,,Stanford University's mission is to promote th...,Stanford University's vision is to be a purpos...,0.043,Stanford University upholds several core value...
4,Yale University,2005,Yale University,,,,,,,,...,,,,,,,Yale is committed to improving the world today...,Yale University aims to improve the world toda...,0.143,"Yale University upholds several core values, i..."

In [26]:
desired_order = [
    'id_',
    'university_name',
    'abbreviation',
    'website',
    'wikipedia',
    'university_type',
    'graduation_year',
    'location',
    'graduation_rate',
    'domestic_student_tuition',
    'international_student_tuition',
    'description',
    'ranking_qs_news_2024',
    'ranking_us_news_2023',
    'ranking_times_rank_2024',
    'ranking_arwu_rank_2023',
    'important_calendar',
    'statistics',
    'faculty',
    'popular_programs',
    'programs',
    'characteristics',
    'others',
    "mission",
    "vision",
    "values",
    "admission_rate",
]
existing_columns = [col for col in desired_order if col in df.columns]

In [27]:
df = df[existing_columns]
df.head()

,id_,university_name,abbreviation,website,wikipedia,university_type,graduation_year,location,graduation_rate,domestic_student_tuition,...,statistics,faculty,popular_programs,programs,characteristics,others,mission,vision,values,admission_rate
0,2001,Princeton University,,,,,,,,,...,,,,,,,Princeton University advances learning through...,Princeton University aims to be a world leader...,Princeton University upholds several core valu...,0.043
1,2002,Massachusetts Institute of Technology,,,,,,,,,...,,,,,,,The mission of the Massachusetts Institute of ...,The mission of MIT is to advance knowledge and...,The Massachusetts Institute of Technology (MIT...,0.143
2,2003,Harvard University,,,,,,,,,...,,,,,,,The mission of Harvard University is to educat...,Harvard University aims to educate the citizen...,Harvard University upholds several core values...,0.039
3,2004,Stanford University,,,,,,,,,...,,,,,,,Stanford University's mission is to promote th...,Stanford University's vision is to be a purpos...,Stanford University upholds several core value...,0.043
4,2005,Yale University,,,,,,,,,...,,,,,,,Yale is committed to improving the world today...,Yale University aims to improve the world toda...,"Yale University upholds several core values, i...",0.143

In [28]:
df.to_csv("./usa_info.csv", index=False)

In [29]:
df = pd.DataFrame.from_dict(result_dict, orient="index").reset_index()
df.head()

,index,id_,university_name,abbreviation,website,wikipedia,university_type,graduation_year,location,graduation_rate,...,statistics,faculty,popular_programs,programs,characteristics,others,mission,vision,admission_rate,values
0,Princeton University,2001,Princeton University,,,,,,,,...,,,,,,,Princeton University advances learning through...,Princeton University aims to be a world leader...,0.043,Princeton University upholds several core valu...
1,Massachusetts Institute of Technology,2002,Massachusetts Institute of Technology,,,,,,,,...,,,,,,,The mission of the Massachusetts Institute of ...,The mission of MIT is to advance knowledge and...,0.143,The Massachusetts Institute of Technology (MIT...
2,Harvard University,2003,Harvard University,,,,,,,,...,,,,,,,The mission of Harvard University is to educat...,Harvard University aims to educate the citizen...,0.039,Harvard University upholds several core values...
3,Stanford University,2004,Stanford University,,,,,,,,...,,,,,,,Stanford University's mission is to promote th...,Stanford University's vision is to be a purpos...,0.043,Stanford University upholds several core value...
4,Yale University,2005,Yale University,,,,,,,,...,,,,,,,Yale is committed to improving the world today...,Yale University aims to improve the world toda...,0.143,"Yale University upholds several core values, i..."

In [6]:
from openai import OpenAI

In [11]:
# usa_universities
client = OpenAI(api_key="")

prompt = """
## Instruction
check if a university is an ivy league, if it is, then return 3 famous people that graduated from the university:
one politician
one CEO level famous people
one celebrity

Example:
Yale University
George H.W. Bush: 41st U.S. President
Meryl Streep: Acclaimed actress
Hillary Clinton: Former Secretary of State
# """

messages = [
            {"role": "system", "content": prompt},
            {
                "role": "user",
                "content": f"university_name: Cornell University",
            },
        ]

In [12]:
response = client.chat.completions.create(messages=messages, model="gpt-4o", temperature=0.0)
result = response.choices[0].message.content

In [13]:
print(result)

Cornell University is an Ivy League university. Here are three famous people who graduated from Cornell:

1. Politician:
   - Ruth Bader Ginsburg: Associate Justice of the Supreme Court of the United States

2. CEO level famous person:
   - David Skorton: Former President and CEO of the Association of American Medical Colleges (AAMC) and former Secretary of the Smithsonian Institution

3. Celebrity:
   - Bill Maher: Comedian, political commentator, and television host