In [1]:
import pandas as pd

input_df = pd.read_excel("./input.xlsx", sheet_name="links")
input_df.drop(columns=["Unnamed: 9"])
input_df.head()

,program_id_,University,Faculty,Program and link,ON Admission Requirement,IB Admission Requirement,BC Admission Requirement,AP Admission Requirement,Language Requirement,Unnamed: 9
0,1,Algoma University,Science,Biology,https://algomau.ca/admissions/admissions-requi...,https://algomau.ca/students/international-stud...,https://algomau.ca/admissions/admissions-requi...,https://algomau.ca/students/international-stud...,https://algomau.ca/admissions/admissions-requi...,NaN
1,2,Algoma University,Science,Environmental Science,https://algomau.ca/admissions/admissions-requi...,https://algomau.ca/students/international-stud...,https://algomau.ca/admissions/admissions-requi...,https://algomau.ca/students/international-stud...,https://algomau.ca/admissions/admissions-requi...,NaN
2,3,Algoma University,Science,Computer Science,https://algomau.ca/admissions/admissions-requi...,https://algomau.ca/students/international-stud...,https://algomau.ca/admissions/admissions-requi...,https://algomau.ca/students/international-stud...,https://algomau.ca/admissions/admissions-requi...,NaN
3,4,Algoma University,Arts,English,https://algomau.ca/admissions/admissions-requi...,https://algomau.ca/students/international-stud...,https://algomau.ca/admissions/admissions-requi...,https://algomau.ca/students/international-stud...,https://algomau.ca/admissions/admissions-requi...,NaN
4,5,Algoma University,Arts,History,https://algomau.ca/admissions/admissions-requi...,https://algomau.ca/students/international-stud...,https://algomau.ca/admissions/admissions-requi...,https://algomau.ca/students/international-stud...,https://algomau.ca/admissions/admissions-requi...,NaN

In [2]:
# sliced_input_df = input_df[200:210]
sliced_input_df = input_df[200:]

In [3]:
input_dict = sliced_input_df.to_dict(orient="index")

In [4]:
from openai import OpenAI
import os
from dotenv import load_dotenv
load_dotenv()

True

In [5]:
program_dict = {}
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
result_dict = {}

def process_row(row):
    def assign(career_direction):
        uni_name = row["University"]
        id_ = row["program_id_"]
        key = f"({id_}, {uni_name}, {program_name})"
        row_json = {
            "program_id_": id_,
            "university_name": uni_name,
            "program_name": program_name,
            "career_direction": career_direction,
        }
        print(key)
        result_dict[key] = row_json
    program_name = row["Program and link"]
    if program_name in program_dict:
        assign(program_dict[program_name])
        return program_dict[program_name]
    prompt = f"""
    I am a student studying {program_name}. 
    Please suggest 5-8 most important potential career directions for me, based on the skills and knowledge typically gained in this program. 
    Provide a list of specific career name (like options or majors) without any description. Separate each path by newline char.
    ## example output: 
        Accounting\nBusiness Technology Management\nEntrepreneurship\nFinance\nGeneral Business Management\nGlobal Supply Chain and Logistics Management\nMarketing\nOperations and Logistics\nOrganizational Behaviour and Human Resources\nReal Estate
    ## format:
        Don't place any leading white space
    """
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=150,
        n=1,
        stop=None,
        temperature=0
    )
    # pt_client.chat.completions.create(messages=messages, model=model, temperature=temperature)
    career_direction = response.choices[0].message.content
    career_direction = career_direction.replace("  \n", "\n").strip()
    program_dict[program_name] = career_direction
    # print(career_direction)
    assign(career_direction)
    return career_direction

In [6]:
import concurrent.futures



# Define the number of threads in the pool
max_threads = 10  # Adjust this based on your system capabilities

# Use ThreadPoolExecutor to manage the threads
with concurrent.futures.ThreadPoolExecutor(max_workers=max_threads) as executor:
    # Submit each task to the thread pool
    futures = {executor.submit(process_row, value): key for key, value in input_dict.items()}

    # Optional: Process the results as they complete
    for future in concurrent.futures.as_completed(futures):
        key = futures[future]
        try:
            result = future.result()
            # Optionally process the result
        except Exception as e:
            print(f"Row processing failed for {key}: {e}")

(209, Nipissing University
, Business)
(203, Nipissing University
, Biology)
(207, Nipissing University
, Adult Education)
(210, Nipissing University
, Criminal Justice)
(206, Nipissing University
, Special Education)
(205, Nipissing University
, Early Childhood Education)
(208, Nipissing University
, Educational Leadership)
(202, Nipissing University
, English Studies)
(204, Nipissing University
, Education)
(214, Nipissing University
, Business Administration)
(220, Nipissing University
, Special Education)
(221, Nipissing University
, Educational Leadership)
(201, Nipissing University
, History)
(213, Nipissing University
, Physical and Health Education)
(224, University of Ottawa, Biology)
(211, Nipissing University
, Nursing)
(217, Nipissing University
, Accounting)
(216, Nipissing University
, Marketing)
(212, Nipissing University
, Social Work)
(215, Nipissing University
, Finance)
(218, Nipissing University
, Human Resources)
(231, University of Ottawa, History)
(219, Nipissing University
, Teaching)
(223, Nipissing University
, Curriculum Studies)
(225, University of Ottawa, Chemistry)
(226, University of Ottawa, Environmental Science)
(227, University of Ottawa, Physics)
(222, Nipissing University
, Early Childhood Studies)
(228, University of Ottawa, Computer Science)
(230, University of Ottawa, English)
(240, University of Ottawa, Business Administration)
(241, University of Ottawa, Finance)
(242, University of Ottawa, Marketing)
(243, University of Ottawa, Accounting)
(229, University of Ottawa, Mathematics and Statistics)
(233, University of Ottawa, Sociology)
(246, University of Ottawa, Nursing)
(232, University of Ottawa, Psychology)
(234, University of Ottawa, Communication)
(236, University of Ottawa, Computer Engineering)
(238, University of Ottawa, Mechanical Engineering)
(239, University of Ottawa, Software Engineering)
(235, University of Ottawa, Civil Engineering)
(244, University of Ottawa, International Business)
(245, University of Ottawa, Health Sciences)
(251, Saint Paul University
, Human Relations)
(248, University of Ottawa, Human Kinetics)
(249, University of Ottawa, Public Health)
(247, University of Ottawa, Biomedical Science)
(253, Saint Paul University
, Public Ethics)
(252, Saint Paul University
, Counselling and Spirituality)
(250, Saint Paul University
, Social Communication)
(254, Saint Paul University
, Conflict Studies)
(255, Saint Paul University
, Ethics)
(257, Saint Paul University
, Epistemology)
(256, Saint Paul University
, Metaphysics)
(258, Saint Paul University
, Political Philosophy)
(259, Saint Paul University
, History of Philosophy)
(261, Saint Paul University
, Pastoral Theology)
(237, University of Ottawa, Electrical Engineering)
(265, Saint Paul University
, Canon Law)
(271, Queen's University
, Psychology)
(272, Queen's University
, Biology)
(264, Saint Paul University
, Historical Theology)
(274, Queen's University
, English)
(275, Queen's University
, History)
(260, Saint Paul University
, Biblical Studies)
(277, Queen's University
, Sociology)
(278, Queen's University
, Mathematics and Statistics)
(262, Saint Paul University
, Systematic Theology)
(266, Saint Paul University
, Matrimonial Law)
(281, Queen's University
, Mechanical Engineering)
(263, Saint Paul University
, Moral Theology)
(283, Queen's University
, Civil Engineering)
(268, Saint Paul University
, Penal Law)
(267, Saint Paul University
, Procedural Law)
(270, Queen's University
, Political Studies)
(269, Saint Paul University
, Comparative Law)
(273, Queen's University
, Economics)
(276, Queen's University
, Philosophy)
(285, Queen's University
, Engineering Physics)
(280, Queen's University
, Chemical Engineering)
(279, Queen's University
, Geography)
(293, Queen's University
, Accounting)
(294, Queen's University
, Marketing)
(284, Queen's University
, Mining Engineering)
(282, Queen's University
, Electrical and Computer Engineering)
(297, Queen's University
, Biomedical Science)
(288, Queen's University
, Commerce)
(286, Queen's University
, Geological Engineering)
(300, Queen's University
, Nursing)
(290, Queen's University
, Executive MBA)
(287, Queen's University
, Applied Mathematics and Engineering)
(289, Queen's University
, MBA)
(292, Queen's University
, Master of Management Analytics)
(295, Queen's University
, Entrepreneurship)
(296, Queen's University
, Life Sciences)
(299, Queen's University
, Health Studies)
(291, Queen's University
, Master of Finance)
(309, Toronto Metropolitan University, Psychology)
(310, Toronto Metropolitan University, Sociology)
(311, Toronto Metropolitan University, History)
(312, Toronto Metropolitan University, English)
(313, Toronto Metropolitan University, Philosophy)
(298, Queen's University
, Biochemistry)
(301, Queen's University
, Occupational Therapy)
(302, Queen's University
, Physical Therapy)
(317, Toronto Metropolitan University, Biology)
(318, Toronto Metropolitan University, Chemistry)
(319, Toronto Metropolitan University, Environmental Science)
(320, Toronto Metropolitan University, Physics)
(306, Queen's University
, Business Law)
(307, Queen's University
, Constitutional Law)
(323, Toronto Metropolitan University, Civil Engineering)
(324, Toronto Metropolitan University, Electrical Engineering)
(325, Toronto Metropolitan University, Mechanical Engineering)
(314, Toronto Metropolitan University, Criminology)
(327, Toronto Metropolitan University, Computer Engineering)
(328, Toronto Metropolitan University, Chemical Engineering)
(308, Queen's University
, Environmental Law)
(304, Queen's University
, JD Program)
(331, Toronto Metropolitan University, Finance)
(332, Toronto Metropolitan University, Marketing)
(303, Queen's University
, Medicine)
(334, Toronto Metropolitan University, Accounting)
(335, Trent University, Environmental Science)
(336, Trent University, Biology)
(337, Trent University, Chemistry)
(338, Trent University, Physics)
(339, Trent University, Computer Science)
(340, Trent University, Business Administration)
(341, Trent University, Finance)
(342, Trent University, Marketing)
(316, Toronto Metropolitan University, Geography and Environmental Studies)
(344, Trent University, Entrepreneurship)
(345, Trent University, Environmental Science)
(315, Toronto Metropolitan University, Politics and Governance)
(347, Trent University, Geography)
(330, Toronto Metropolitan University, Business Management)
(321, Toronto Metropolitan University, Mathematics)
(350, Trent University, Mathematics)
(326, Toronto Metropolitan University, Biomedical Engineering)
(352, Trent University, Computer Science)
(333, Toronto Metropolitan University, Hospitality and Tourism Management)
(322, Toronto Metropolitan University, Aerospace Engineering)
(355, Trent University, Psychology)
(356, Trent University, Sociology)
(357, Trent University, History)
(343, Trent University, Human Resource Management)
(359, Trent University, Political Studies)
(360, Western University, Computer Science)
(361, Western University, Biology)
(362, Western University, Chemistry)
(363, Western University, Environmental Science)
(364, Western University, Physics)
(365, Western University, Mathematics and Statistics)
(346, Trent University, Environmental Studies)
(349, Trent University, Indigenous Environmental Studies)
(368, Western University, Psychology)
(369, Western University, Sociology)
(305, Queen's University
, International Law)
(371, Western University, Economics)
(372, Western University, Geography)
(348, Trent University, Ecological Restoration)
(374, Western University, History)
(375, Western University, Business)
(376, Western University, Civil Engineering)
(377, Western University, Mechanical Engineering)
(378, Western University, Electrical Engineering)
(379, Western University, Chemical Engineering)
(380, Western University, Software Engineering)
(354, Trent University, Applied Mathematics)
(353, Trent University, Data Science)
(351, Trent University, Statistics)
(384, Western University, Business Administration)
(385, Western University, Finance)
(386, Western University, Marketing)
(387, Western University, Accounting)
(388, Western University, International Business)
(389, Western University, Entrepreneurship)
(366, Western University, Earth Sciences)
(367, Western University, Neuroscience)
(392, Western University, Medicine)
(358, Trent University, Anthropology)
(394, Western University, Nursing)
(390, Western University, Leadership)
(370, Western University, Political Science)
(373, Western University, Anthropology)
(398, Western University, Biochemistry)
(382, Western University, Environmental Engineering)
(400, Wilfrid Laurier University, Biology)
(401, Wilfrid Laurier University, Chemistry)
(402, Wilfrid Laurier University, Physics)
(403, Wilfrid Laurier University, Psychology)
(404, Wilfrid Laurier University, Computer Science)
(405, Wilfrid Laurier University, Psychology)
(406, Wilfrid Laurier University, Sociology)
(407, Wilfrid Laurier University, History)
(408, Wilfrid Laurier University, English)
(409, Wilfrid Laurier University, Philosophy)
(410, Wilfrid Laurier University, Business Administration)
(411, Wilfrid Laurier University, Economics)
(412, Wilfrid Laurier University, Finance)
(413, Wilfrid Laurier University, Marketing)
(414, Wilfrid Laurier University, Accounting)
(415, Wilfrid Laurier University, Criminology)
(416, Wilfrid Laurier University, Social Work)
(417, Wilfrid Laurier University, Health Studies)
(418, Wilfrid Laurier University, Leadership)
(419, Wilfrid Laurier University, Psychology)
(391, Western University, Supply Chain Management)
(383, Western University, Integrated Engineering)
(381, Western University, Mechatronic Systems Engineering)
(393, Western University, Dentistry)
(421, Wilfrid Laurier University, Composition)
(425, University of Windsor, Biology)
(426, University of Windsor, Chemistry)
(427, University of Windsor, Environmental Science)
(428, University of Windsor, Physics)
(429, University of Windsor, Computer Science)
(430, University of Windsor, Psychology)
(431, University of Windsor, Sociology)
(432, University of Windsor, History)
(433, University of Windsor, English)
(434, University of Windsor, Philosophy)
(435, University of Windsor, Civil Engineering)
(436, University of Windsor, Mechanical Engineering)
(437, University of Windsor, Electrical Engineering)
(329, Toronto Metropolitan University, Industrial Engineering)
(439, University of Windsor, Environmental Engineering)
(440, University of Windsor, Business Administration)
(441, University of Windsor, Accounting)
(442, University of Windsor, Finance)
(443, University of Windsor, Marketing)
(444, University of Windsor, Human Resources)
(445, University of Windsor, Nursing)
(396, Western University, Epidemiology and Biostatistics)
(399, Western University, Microbiology and Immunology)
(420, Wilfrid Laurier University, Performance)
(395, Western University, Medical Sciences)
(450, York University, Biology)
(451, York University, Chemistry)
(452, York University, Environmental Science)
(453, York University, Physics)
(454, York University, Mathematics)
(455, York University, Computer Science)
(397, Western University, Anatomy and Cell Biology)
(423, Wilfrid Laurier University, Music Education)
(458, York University, Psychology)
(459, York University, Sociology)
(460, York University, History)
(461, York University, English)
(462, York University, Philosophy)
(463, York University, Economics)
(464, York University, Political Science)
(465, York University, Criminology)
(466, York University, Civil Engineering)
(467, York University, Electrical Engineering)
(468, York University, Mechanical Engineering)
(469, York University, Computer Engineering)
(470, York University, Software Engineering)
(422, Wilfrid Laurier University, Music Therapy)
(424, Wilfrid Laurier University, Community Music)
(438, University of Windsor, Industrial Engineering)
(474, York University, Business Administration)
(475, York University, Finance)
(476, York University, Marketing)
(477, York University, Accounting)
(478, York University, International Business)
(449, University of Windsor, Doctor of Nursing Practice (DNP))
(447, University of Windsor, Nursing (Post RN))
(481, York University, Entrepreneurship)
(482, York University, Health Sciences)
(483, York University, Nursing)
(471, York University, Geomatics Engineering)
(485, York University, Public Health)
(486, York University, Psychology)
(456, York University, Astronomy)
(488, York University, Neuroscience)
(448, University of Windsor, Master of Nursing (MN))
(446, University of Windsor, Collaborative Nursing Program)
(472, York University, Space Engineering)
(473, York University, Earth and Atmospheric Science)
(479, York University, Strategic Management)
(480, York University, Operations Management)
(489, York University, Health Policy and Management)
(484, York University, Kinesiology)
(490, Ontario College of Art and Design University, Drawing and Painting)
(492, Ontario College of Art and Design University, Printmaking)
(487, York University, Global Health)
(493, Ontario College of Art and Design University, Sculpture/Installation)
(494, Ontario College of Art and Design University, Criticism and Curatorial Practice)
(491, Ontario College of Art and Design University, Photography)
(503, Ontario College of Art and Design University, Criticism and Curatorial Practice)
(497, Ontario College of Art and Design University, Environmental Design)
(505, Ontario College of Art and Design University, English)
(506, Ontario College of Art and Design University, History)
(507, Ontario College of Art and Design University, Philosophy)
(508, Ontario College of Art and Design University, Sociology)
(496, Ontario College of Art and Design University, Industrial Design)
(510, University of Ontario Institute of Technology, Biology)
(511, University of Ontario Institute of Technology, Chemistry)
(512, University of Ontario Institute of Technology, Environmental Science)
(513, University of Ontario Institute of Technology, Physics)
(514, University of Ontario Institute of Technology, Mathematics and Statistics)
(515, University of Ontario Institute of Technology, Mechanical Engineering)
(516, University of Ontario Institute of Technology, Electrical Engineering)
(517, University of Ontario Institute of Technology, Software Engineering)
(518, University of Ontario Institute of Technology, Computer Engineering)
(495, Ontario College of Art and Design University, Graphic Design)
(520, University of Ontario Institute of Technology, Business Administration)
(521, University of Ontario Institute of Technology, Finance)
(522, University of Ontario Institute of Technology, Marketing)
(523, University of Ontario Institute of Technology, Accounting)
(498, Ontario College of Art and Design University, Advertising)
(525, University of Ontario Institute of Technology, Health Sciences)
(526, University of Ontario Institute of Technology, Nursing)
(501, Ontario College of Art and Design University, Digital Futures)
(528, University of Ontario Institute of Technology, Kinesiology)
(529, University of Ontario Institute of Technology, Public Health)
(530, University of Ontario Institute of Technology, Criminology)
(502, Ontario College of Art and Design University, Integrated Media)
(532, University of Ontario Institute of Technology, Political Science)
(533, University of Ontario Institute of Technology, Psychology)
(500, Ontario College of Art and Design University, Visual and Critical Studies)
(535, University of British Columbia, Computer Science)
(536, University of British Columbia, Biology)
(537, University of British Columbia, Chemistry)
(538, University of British Columbia, Physics)
(539, University of British Columbia, Mathematics)
(499, Ontario College of Art and Design University, Illustration)
(541, University of British Columbia, Environmental Science)
(542, University of British Columbia, Microbiology and Immunology)
(543, University of British Columbia, Statistics)
(509, Ontario College of Art and Design University, Indigenous Visual Culture)
(545, University of British Columbia, English)
(546, University of British Columbia, History)
(547, University of British Columbia, Psychology)
(548, University of British Columbia, Political Science)
(549, University of British Columbia, Sociology)
(550, University of British Columbia, Anthropology)
(551, University of British Columbia, Economics)
(552, University of British Columbia, Geography)
(457, York University, Biophysics)
(554, University of British Columbia, Philosophy)
(555, University of British Columbia, Civil Engineering)
(556, University of British Columbia, Mechanical Engineering)
(557, University of British Columbia, Electrical and Computer Engineering)
(524, University of Ontario Institute of Technology, Information Technology)
(559, University of British Columbia, Biomedical Engineering)
(504, Ontario College of Art and Design University, Art and Social Change)
(561, University of British Columbia, Mining Engineering)
(562, University of British Columbia, Engineering Physics)
(563, University of British Columbia, Environmental Engineering)
(564, University of British Columbia, Integrated Engineering)
(565, University of British Columbia, Business Administration)
(566, University of British Columbia, Finance)
(567, University of British Columbia, Marketing)
(568, University of British Columbia, Accounting)
(569, University of British Columbia, International Business)
(519, University of Ontario Institute of Technology, Automotive Engineering)
(534, University of Ontario Institute of Technology, Communication and Digital Media Studies)
(572, University of British Columbia, Strategic Management)
(573, University of British Columbia, Entrepreneurship)
(531, University of Ontario Institute of Technology, Legal Studies)
(540, University of British Columbia, Earth and Ocean Sciences)
(544, University of British Columbia, Biochemistry and Molecular Biology)
(527, University of Ontario Institute of Technology, Medical Laboratory Science)
(578, University of British Columbia, Special Education)
(558, University of British Columbia, Chemical and Biological Engineering)
(580, University of British Columbia, Early Childhood Education)
(570, University of British Columbia, Operations and Logistics)
(553, University of British Columbia, Asian Studies)
(560, University of British Columbia, Materials Engineering)
(575, University of British Columbia, Teacher Education)
(585, University of British Columbia, Medicine)
(586, University of British Columbia, Dentistry)
(587, University of British Columbia, Nursing)
(588, University of British Columbia, Public Health)
(571, University of British Columbia, Real Estate)
(576, University of British Columbia, Curriculum and Pedagogy)
(591, Simon Fraser University, Chemistry)
(592, Simon Fraser University, Environmental Science)
(593, Simon Fraser University, Physics)
(594, Simon Fraser University, Mathematics)
(595, Simon Fraser University, English)
(596, Simon Fraser University, History)
(597, Simon Fraser University, Psychology)
(598, Simon Fraser University, Sociology)
(599, Simon Fraser University, Political Science)
(574, University of British Columbia, Organizational Behaviour and Human Resources)
(582, University of British Columbia, Indigenous Education)
(602, Simon Fraser University, Mechatronic Systems Engineering)
(581, University of British Columbia, Adult Learning and Education)
(579, University of British Columbia, Educational and Counselling Psychology)
(605, Simon Fraser University, Business Administration)
(606, Simon Fraser University, Finance)
(607, Simon Fraser University, Marketing)
(608, Simon Fraser University, Accounting)
(609, Simon Fraser University, International Business)
(610, Simon Fraser University, Health Sciences)
(611, Simon Fraser University, Public Health)

In [7]:
print(result_dict)

{'(209, Nipissing University\n, Business)': {'program_id_': 209, 'university_name': 'Nipissing University\n', 'program_name': 'Business', 'career_direction': 'Accounting\nBusiness Technology Management\nEntrepreneurship\nFinance\nGeneral Business Management\nGlobal Supply Chain and Logistics Management\nMarketing\nOperations and Logistics\nOrganizational Behaviour and Human Resources\nReal Estate\nBusiness Analytics\nConsulting\nInternational Business\nSales Management\nCorporate Strategy\nProject Management\nRisk Management\nPublic Relations\nInvestment Banking\nHuman Resource Management'}, '(203, Nipissing University\n, Biology)': {'program_id_': 203, 'university_name': 'Nipissing University\n', 'program_name': 'Biology', 'career_direction': 'Biotechnology\nMicrobiology\nGenetics\nEnvironmental Science\nMarine Biology\nEcology\nZoology\nBotany\nBiomedical Research\nPharmaceutical Sales\nForensic Science\nBioinformatics\nWildlife Conservation\nAgricultural Science\nImmunology\nPublic Health\nClinical Laboratory Science\nBiostatistics\nToxicology\nScience Education'}, '(207, Nipissing University\n, Adult Education)': {'program_id_': 207, 'university_name': 'Nipissing University\n', 'program_name': 'Adult Education', 'career_direction': 'Adult Education Instructor\nCorporate Trainer\nCurriculum Developer\nEducational Consultant\nInstructional Designer\nTraining and Development Manager\nCommunity Education Coordinator\nAdult Literacy and GED Instructor\nWorkforce Development Specialist\nOnline Learning Facilitator\nContinuing Education Program Coordinator\nProfessional Development Specialist\nAcademic Advisor\nCareer Counselor\nHuman Resources Specialist\nLearning and Development Specialist\nProgram Evaluator\nEducational Program Manager\nDistance Education Specialist\nNonprofit Education Director'}, '(210, Nipissing University\n, Criminal Justice)': {'program_id_': 210, 'university_name': 'Nipissing University\n', 'program_name': 'Criminal Justice', 'career_direction': 'Corrections Officer\nProbation Officer\nParole Officer\nPolice Officer\nDetective\nFederal Agent (FBI, DEA, ATF, etc.)\nCrime Scene Investigator\nForensic Scientist\nCriminal Profiler\nCourt Clerk\nLegal Assistant\nVictim Advocate\nJuvenile Justice Counselor\nSecurity Manager\nLoss Prevention Specialist\nPrivate Investigator\nEmergency Management Coordinator\nIntelligence Analyst\nBorder Patrol Agent\nCustoms Officer'}, '(206, Nipissing University\n, Special Education)': {'program_id_': 206, 'university_name': 'Nipissing University\n', 'program_name': 'Special Education', 'career_direction': 'Special Education Teacher\nResource Room Teacher\nInclusion Specialist\nBehavioral Specialist\nEducational Diagnostician\nSpecial Education Advocate\nTransition Coordinator\nEarly Intervention Specialist\nAutism Specialist\nLearning Disabilities Specialist\nSpeech-Language Pathologist\nOccupational Therapist\nSchool Counselor\nAssistive Technology Specialist\nSpecial Education Administrator\nEducational Consultant\nRehabilitation Counselor\nAdaptive Physical Education Teacher\nDevelopmental Therapist\nChild Life Specialist'}, '(205, Nipissing University\n, Early Childhood Education)': {'program_id_': 205, 'university_name': 'Nipissing University\n', 'program_name': 'Early Childhood Education', 'career_direction': 'Preschool Teacher\nKindergarten Teacher\nChildcare Center Director\nEarly Childhood Education Consultant\nSpecial Education Teacher\nEarly Intervention Specialist\nFamily Support Specialist\nChild Development Researcher\nCurriculum Developer\nEducation Program Coordinator\nNanny or Au Pair\nChild Life Specialist\nEarly Childhood Policy Advocate\nParent Educator\nYouth Program Director\nEducational Toy Designer\nEarly Childhood Education Professor\nSchool Counselor\nReading Specialist\nEducational Administrator'}, '(208, Nipissing University\n, Educational Leadership)': {'program_id_': 208, 'university_name': 'Nipissing University\n', 'program_name': 'Educational Leadership', 'career_direction': 'School Principal\nAssistant Principal\nDistrict Administrator\nCurriculum Developer\nInstructional Coordinator\nEducation Consultant\nHigher Education Administrator\nAcademic Dean\nDirector of Student Services\nEducational Policy Analyst\nNonprofit Education Director\nCorporate Trainer\nEducational Technology Specialist\nSchool Superintendent\nDirector of Admissions\nDirector of Special Education\nProfessional Development Coordinator\nEducation Program Director\nEducational Researcher\nOnline Learning Coordinator'}, '(202, Nipissing University\n, English Studies)': {'program_id_': 202, 'university_name': 'Nipissing University\n', 'program_name': 'English Studies', 'career_direction': 'Copywriter\nEditor\nContent Strategist\nTechnical Writer\nPublic Relations Specialist\nJournalist\nSocial Media Manager\nMarketing Coordinator\nCommunications Specialist\nGrant Writer\nProofreader\nSpeechwriter\nPublishing Assistant\nLiterary Agent\nEnglish Teacher\nESL Instructor\nCorporate Trainer\nResearch Analyst\nLibrarian\nHuman Resources Specialist'}, '(204, Nipissing University\n, Education)': {'program_id_': 204, 'university_name': 'Nipissing University\n', 'program_name': 'Education', 'career_direction': 'Teacher\nSchool Administrator\nCurriculum Developer\nEducational Consultant\nInstructional Coordinator\nSpecial Education Teacher\nEducation Policy Analyst\nEducation Researcher\nCorporate Trainer\nAcademic Advisor\nSchool Counselor\nEducation Technology Specialist\nAdult Education Instructor\nLibrarian\nEducation Program Manager\nOnline Course Developer\nEarly Childhood Educator\nHigher Education Administrator\nEducation Sales Representative\nNonprofit Education Coordinator'}, '(214, Nipissing University\n, Business Administration)': {'program_id_': 214, 'university_name': 'Nipissing University\n', 'program_name': 'Business Administration', 'career_direction': 'Accounting\nBusiness Technology Management\nEntrepreneurship\nFinance\nGeneral Business Management\nGlobal Supply Chain and Logistics Management\nMarketing\nOperations and Logistics\nOrganizational Behaviour and Human Resources\nReal Estate'}, '(220, Nipissing University\n, Special Education)': {'program_id_': 220, 'university_name': 'Nipissing University\n', 'program_name': 'Special Education', 'career_direction': 'Special Education Teacher\nResource Room Teacher\nInclusion Specialist\nBehavioral Specialist\nEducational Diagnostician\nSpecial Education Advocate\nTransition Coordinator\nEarly Intervention Specialist\nAutism Specialist\nLearning Disabilities Specialist\nSpeech-Language Pathologist\nOccupational Therapist\nSchool Counselor\nAssistive Technology Specialist\nSpecial Education Administrator\nEducational Consultant\nRehabilitation Counselor\nAdaptive Physical Education Teacher\nDevelopmental Therapist\nChild Life Specialist'}, '(221, Nipissing University\n, Educational Leadership)': {'program_id_': 221, 'university_name': 'Nipissing University\n', 'program_name': 'Educational Leadership', 'career_direction': 'School Principal\nAssistant Principal\nDistrict Administrator\nCurriculum Developer\nInstructional Coordinator\nEducation Consultant\nHigher Education Administrator\nAcademic Dean\nDirector of Student Services\nEducational Policy Analyst\nNonprofit Education Director\nCorporate Trainer\nEducational Technology Specialist\nSchool Superintendent\nDirector of Admissions\nDirector of Special Education\nProfessional Development Coordinator\nEducation Program Director\nEducational Researcher\nOnline Learning Coordinator'}, '(201, Nipissing University\n, History)': {'program_id_': 201, 'university_name': 'Nipissing University\n', 'program_name': 'History', 'career_direction': 'Historian\nArchivist\nMuseum Curator\nHistory Teacher\nResearch Analyst\nCultural Resource Manager\nGenealogist\nHistorical Consultant\nPublic Historian\nDocumentary Editor\nPolicy Advisor\nHeritage Manager\nLibrarian\nTour Guide\nWriter/Author\nEditor\nJournalist\nLegal Researcher\nIntelligence Analyst\nDiplomat\nNonprofit Coordinator\nPublic Relations Specialist\nMarket Research Analyst\nContent Strategist\nGrant Writer'}, '(213, Nipissing University\n, Physical and Health Education)': {'program_id_': 213, 'university_name': 'Nipissing University\n', 'program_name': 'Physical and Health Education', 'career_direction': 'Athletic Trainer\nPhysical Education Teacher\nHealth Educator\nSports Coach\nExercise Physiologist\nRecreation Director\nFitness Instructor\nSports Nutritionist\nOccupational Therapist\nPhysical Therapist\nSports Psychologist\nWellness Coordinator\nKinesiologist\nStrength and Conditioning Coach\nPublic Health Administrator\nCorporate Wellness Consultant\nSports Management Professional\nRehabilitation Specialist\nCommunity Health Worker\nYouth Sports Coordinator'}, '(224, University of Ottawa, Biology)': {'program_id_': 224, 'university_name': 'University of Ottawa', 'program_name': 'Biology', 'career_direction': 'Biotechnology\nMicrobiology\nGenetics\nEnvironmental Science\nMarine Biology\nEcology\nZoology\nBotany\nBiomedical Research\nPharmaceutical Sales\nForensic Science\nBioinformatics\nWildlife Conservation\nAgricultural Science\nImmunology\nPublic Health\nClinical Laboratory Science\nBiostatistics\nToxicology\nScience Education'}, '(211, Nipissing University\n, Nursing)': {'program_id_': 211, 'university_name': 'Nipissing University\n', 'program_name': 'Nursing', 'career_direction': 'Registered Nurse (RN)\nNurse Practitioner (NP)\nClinical Nurse Specialist (CNS)\nNurse Anesthetist (CRNA)\nNurse Midwife\nNurse Educator\nNurse Researcher\nPublic Health Nurse\nSchool Nurse\nTravel Nurse\nPediatric Nurse\nGeriatric Nurse\nOncology Nurse\nCritical Care Nurse\nEmergency Room Nurse\nOperating Room Nurse\nHome Health Nurse\nHospice Nurse\nOccupational Health Nurse\nNurse Administrator'}, '(217, Nipissing University\n, Accounting)': {'program_id_': 217, 'university_name': 'Nipissing University\n', 'program_name': 'Accounting', 'career_direction': 'Accounting\nAuditing\nTaxation\nFinancial Analysis\nManagement Accounting\nForensic Accounting\nInternal Auditing\nPublic Accounting\nBudget Analysis\nCost Accounting\nGovernment Accounting\nCorporate Finance\nInvestment Banking\nFinancial Planning\nRisk Management\nCompliance\nTreasury Management\nConsulting\nNonprofit Accounting\nEnvironmental Accounting'}, '(216, Nipissing University\n, Marketing)': {'program_id_': 216, 'university_name': 'Nipissing University\n', 'program_name': 'Marketing', 'career_direction': 'Advertising Manager\nBrand Manager\nMarket Research Analyst\nDigital Marketing Specialist\nSocial Media Manager\nPublic Relations Specialist\nContent Marketing Manager\nSEO Specialist\nProduct Manager\nSales Manager\nMarketing Coordinator\nEvent Planner\nMedia Buyer\nEmail Marketing Specialist\nCustomer Relationship Manager\nMarketing Consultant\nRetail Manager\nE-commerce Manager\nMarketing Analyst\nPromotions Manager'}, '(212, Nipissing University\n, Social Work)': {'program_id_': 212, 'university_name': 'Nipissing University\n', 'program_name': 'Social Work', 'career_direction': 'Child Welfare Social Worker\nSchool Social Worker\nMedical Social Worker\nMental Health Counselor\nSubstance Abuse Counselor\nClinical Social Worker\nCommunity Outreach Worker\nGerontological Social Worker\nPolicy Analyst\nSocial Work Administrator\nProbation Officer\nFamily Therapist\nCrisis Intervention Specialist\nYouth Services Specialist\nVictim Advocate\nRehabilitation Counselor\nHousing Coordinator\nHuman Services Manager\nAdoption Specialist\nForensic Social Worker'}, '(215, Nipissing University\n, Finance)': {'program_id_': 215, 'university_name': 'Nipissing University\n', 'program_name': 'Finance', 'career_direction': 'Investment Banking\nFinancial Planning\nCorporate Finance\nAsset Management\nRisk Management\nPrivate Equity\nVenture Capital\nCommercial Banking\nFinancial Analysis\nTreasury Management\nInsurance Underwriting\nCredit Analysis\nHedge Fund Management\nQuantitative Analysis\nWealth Management\nCompliance and Regulatory Affairs\nFinancial Consulting\nReal Estate Finance\nMergers and Acquisitions\nEquity Research'}, '(218, Nipissing University\n, Human Resources)': {'program_id_': 218, 'university_name': 'Nipissing University\n', 'program_name': 'Human Resources', 'career_direction': 'Human Resources Specialist\nRecruitment Coordinator\nEmployee Relations Manager\nCompensation and Benefits Analyst\nTraining and Development Manager\nHR Consultant\nTalent Acquisition Specialist\nHR Information Systems Analyst\nLabor Relations Specialist\nDiversity and Inclusion Manager\nHR Business Partner\nOrganizational Development Consultant\nWorkforce Planning Analyst\nEmployee Experience Manager\nHR Compliance Officer'}, '(231, University of Ottawa, History)': {'program_id_': 231, 'university_name': 'University of Ottawa', 'program_name': 'History', 'career_direction': 'Historian\nArchivist\nMuseum Curator\nHistory Teacher\nResearch Analyst\nCultural Resource Manager\nGenealogist\nHistorical Consultant\nPublic Historian\nDocumentary Editor\nPolicy Advisor\nHeritage Manager\nLibrarian\nTour Guide\nWriter/Author\nEditor\nJournalist\nLegal Researcher\nIntelligence Analyst\nDiplomat\nNonprofit Coordinator\nPublic Relations Specialist\nMarket Research Analyst\nContent Strategist\nGrant Writer'}, '(219, Nipissing University\n, Teaching)': {'program_id_': 219, 'university_name': 'Nipissing University\n', 'program_name': 'Teaching', 'career_direction': 'Teacher\nEducational Consultant\nCurriculum Developer\nSchool Administrator\nInstructional Coordinator\nSpecial Education Teacher\nEducational Researcher\nCorporate Trainer\nOnline Course Developer\nEducation Policy Analyst\nAcademic Advisor\nEducation Technology Specialist\nAdult Education Instructor\nTutoring Center Manager\nLibrary Media Specialist\nEducation Program Director\nYouth Program Coordinator\nEducation Outreach Specialist\nHigher Education Administrator\nStudent Affairs Coordinator'}, '(223, Nipissing University\n, Curriculum Studies)': {'program_id_': 223, 'university_name': 'Nipissing University\n', 'program_name': 'Curriculum Studies', 'career_direction': 'Curriculum Developer\nInstructional Coordinator\nEducational Consultant\nAcademic Advisor\nEducation Policy Analyst\nTraining and Development Specialist\nCorporate Trainer\nEducational Program Director\nTextbook Author/Editor\nOnline Course Designer\nEducation Researcher\nSchool Administrator\nProfessional Development Coordinator\nLearning and Development Manager\nHigher Education Administrator'}, '(225, University of Ottawa, Chemistry)': {'program_id_': 225, 'university_name': 'University of Ottawa', 'program_name': 'Chemistry', 'career_direction': 'Analytical Chemist\nBiochemist\nChemical Engineer\nEnvironmental Scientist\nForensic Scientist\nMaterials Scientist\nPharmaceutical Chemist\nQuality Control Chemist\nResearch Scientist\nToxicologist\nLaboratory Technician\nFood Scientist\nPatent Examiner\nRegulatory Affairs Specialist\nScience Writer\nTechnical Sales Representative\nWater Chemist\nClinical Research Associate\nProcess Development Scientist\nChemical Safety Officer'}, '(226, University of Ottawa, Environmental Science)': {'program_id_': 226, 'university_name': 'University of Ottawa', 'program_name': 'Environmental Science', 'career_direction': 'Environmental Consultant\nWildlife Biologist\nEnvironmental Educator\nSustainability Specialist\nConservation Scientist\nEnvironmental Engineer\nHydrologist\nEnvironmental Health and Safety Manager\nClimate Change Analyst\nEnvironmental Policy Analyst\nEcologist\nNatural Resource Manager\nEnvironmental Planner\nMarine Biologist\nRenewable Energy Specialist\nEnvironmental Lawyer\nGeospatial Analyst\nAir Quality Specialist\nSoil Scientist\nEnvironmental Toxicologist'}, '(227, University of Ottawa, Physics)': {'program_id_': 227, 'university_name': 'University of Ottawa', 'program_name': 'Physics', 'career_direction': 'Data Scientist\nResearch Scientist\nQuantitative Analyst\nMedical Physicist\nAerospace Engineer\nSoftware Developer\nSystems Analyst\nPatent Examiner\nTechnical Writer\nScience Communicator\nEnvironmental Consultant\nEnergy Analyst\nAstronomer\nGeophysicist\nBiophysicist\nNuclear Engineer\nOptical Engineer\nMaterials Scientist\nMeteorologist\nSeismologist'}, '(222, Nipissing University\n, Early Childhood Studies)': {'program_id_': 222, 'university_name': 'Nipissing University\n', 'program_name': 'Early Childhood Studies', 'career_direction': 'Early Childhood Educator\nChildcare Center Director\nPreschool Teacher\nSpecial Education Assistant\nFamily Support Worker\nChild Development Specialist\nEarly Intervention Specialist\nChild Life Specialist\nNanny\nEarly Childhood Program Coordinator\nEducational Consultant\nParent Educator\nYouth Program Director\nEarly Childhood Policy Advocate\nChildcare Licensing Specialist\nEarly Childhood Curriculum Developer\nEarly Childhood Researcher\nEarly Childhood Trainer\nEarly Childhood Administrator\nEarly Childhood Advocate'}, '(228, University of Ottawa, Computer Science)': {'program_id_': 228, 'university_name': 'University of Ottawa', 'program_name': 'Computer Science', 'career_direction': 'Software Development\nData Science\nCybersecurity\nArtificial Intelligence and Machine Learning\nCloud Computing\nNetwork Engineering\nDatabase Administration\nWeb Development\nMobile App Development\nGame Development\nDevOps Engineering\nSystems Analysis\nIT Project Management\nBusiness Analysis\nUser Experience (UX) Design\nRobotics Engineering\nEmbedded Systems Engineering\nIT Consulting\nTechnical Support Engineering\nQuality Assurance (QA) Testing\nResearch and Development (R&D)'}, '(230, University of Ottawa, English)': {'program_id_': 230, 'university_name': 'University of Ottawa', 'program_name': 'English', 'career_direction': 'Copywriting\nContent Writing\nEditing\nPublishing\nJournalism\nPublic Relations\nTechnical Writing\nTeaching\nTranslation\nLibrarianship\nSpeech Writing\nSocial Media Management\nAdvertising\nCorporate Communications\nGrant Writing\nCreative Writing\nScreenwriting\nLiterary Agent\nBook Reviewing\nProofreading'}, '(240, University of Ottawa, Business Administration)': {'program_id_': 240, 'university_name': 'University of Ottawa', 'program_name': 'Business Administration', 'career_direction': 'Accounting\nBusiness Technology Management\nEntrepreneurship\nFinance\nGeneral Business Management\nGlobal Supply Chain and Logistics Management\nMarketing\nOperations and Logistics\nOrganizational Behaviour and Human Resources\nReal Estate'}, '(241, University of Ottawa, Finance)': {'program_id_': 241, 'university_name': 'University of Ottawa', 'program_name': 'Finance', 'career_direction': 'Investment Banking\nFinancial Planning\nCorporate Finance\nAsset Management\nRisk Management\nPrivate Equity\nVenture Capital\nCommercial Banking\nFinancial Analysis\nTreasury Management\nInsurance Underwriting\nCredit Analysis\nHedge Fund Management\nQuantitative Analysis\nWealth Management\nCompliance and Regulatory Affairs\nFinancial Consulting\nReal Estate Finance\nMergers and Acquisitions\nEquity Research'}, '(242, University of Ottawa, Marketing)': {'program_id_': 242, 'university_name': 'University of Ottawa', 'program_name': 'Marketing', 'career_direction': 'Advertising Manager\nBrand Manager\nMarket Research Analyst\nDigital Marketing Specialist\nSocial Media Manager\nPublic Relations Specialist\nContent Marketing Manager\nSEO Specialist\nProduct Manager\nSales Manager\nMarketing Coordinator\nEvent Planner\nMedia Buyer\nEmail Marketing Specialist\nCustomer Relationship Manager\nMarketing Consultant\nRetail Manager\nE-commerce Manager\nMarketing Analyst\nPromotions Manager'}, '(243, University of Ottawa, Accounting)': {'program_id_': 243, 'university_name': 'University of Ottawa', 'program_name': 'Accounting', 'career_direction': 'Accounting\nAuditing\nTaxatio

In [8]:
print(len(result_dict))

514

In [9]:
df = pd.DataFrame.from_dict(result_dict, orient="index").reset_index()
df.head(20)

,index,program_id_,university_name,program_name,career_direction
0,"(209, Nipissing University\n, Business)",209,Nipissing University\n,Business,Accounting\nBusiness Technology Management\nEn...
1,"(203, Nipissing University\n, Biology)",203,Nipissing University\n,Biology,Biotechnology\nMicrobiology\nGenetics\nEnviron...
2,"(207, Nipissing University\n, Adult Education)",207,Nipissing University\n,Adult Education,Adult Education Instructor\nCorporate Trainer\...
3,"(210, Nipissing University\n, Criminal Justice)",210,Nipissing University\n,Criminal Justice,Corrections Officer\nProbation Officer\nParole...
4,"(206, Nipissing University\n, Special Education)",206,Nipissing University\n,Special Education,Special Education Teacher\nResource Room Teach...
5,"(205, Nipissing University\n, Early Childhood ...",205,Nipissing University\n,Early Childhood Education,Preschool Teacher\nKindergarten Teacher\nChild...
6,"(208, Nipissing University\n, Educational Lead...",208,Nipissing University\n,Educational Leadership,School Principal\nAssistant Principal\nDistric...
7,"(202, Nipissing University\n, English Studies)",202,Nipissing University\n,English Studies,Copywriter\nEditor\nContent Strategist\nTechni...
8,"(204, Nipissing University\n, Education)",204,Nipissing University\n,Education,Teacher\nSchool Administrator\nCurriculum Deve...
9,"(214, Nipissing University\n, Business Adminis...",214,Nipissing University\n,Business Administration,Accounting\nBusiness Technology Management\nEn...
10,"(220, Nipissing University\n, Special Education)",220,Nipissing University\n,Special Education,Special Education Teacher\nResource Room Teach...
11,"(221, Nipissing University\n, Educational Lead...",221,Nipissing University\n,Educational Leadership,School Principal\nAssistant Principal\nDistric...
12,"(201, Nipissing University\n, History)",201,Nipissing University\n,History,Historian\nArchivist\nMuseum Curator\nHistory ...
13,"(213, Nipissing University\n, Physical and Hea...",213,Nipissing University\n,Physical and Health Education,Athletic Trainer\nPhysical Education Teacher\n...
14,"(224, University of Ottawa, Biology)",224,University of Ottawa,Biology,Biotechnology\nMicrobiology\nGenetics\nEnviron...
15,"(211, Nipissing University\n, Nursing)",211,Nipissing University\n,Nursing,Registered Nurse (RN)\nNurse Practitioner (NP)...
16,"(217, Nipissing University\n, Accounting)",217,Nipissing University\n,Accounting,Accounting\nAuditing\nTaxation\nFinancial Anal...
17,"(216, Nipissing University\n, Marketing)",216,Nipissing University\n,Marketing,Advertising Manager\nBrand Manager\nMarket Res...
18,"(212, Nipissing University\n, Social Work)",212,Nipissing University\n,Social Work,Child Welfare Social Worker\nSchool Social Wor...
19,"(215, Nipissing University\n, Finance)",215,Nipissing University\n,Finance,Investment Banking\nFinancial Planning\nCorpor...

In [10]:
df.to_csv("./program_output_rerun.csv", index=False, encoding="utf-8")