# Set up env

In [1]:
%%sh
# current_path=$(pwd)
# parent_dir=$(dirname "$current_dir")
export PROJECT_HOME="/home/ivan/Uforse/university_crawl"
echo $PROJECT_HOME
if [ -f "${PROJECT_HOME}/build" ]; then
    echo "Found build in PROJECT_HOME. Sourcing now..."
    . "${PROJECT_HOME}/build"
    echo "build executed successfully."
else
    echo "Error: build not found in PROJECT_HOME."
fi

/home/ivan/Uforse/university_crawl
Found build in PROJECT_HOME. Sourcing now...
Obtaining file:///home/ivan/Uforse/university_crawl/university_info_generator
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pandas in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.3) (2.2.2)
Requirement already satisfied: numpy in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.3) (1.26.4)
Requirement already satisfied: gspread in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.3) (6.1.0)
Requirement already satisfied: oauth2client in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.3) (4.1.3)
Requirement already satisfied: openai in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.3) (1.28.0)
Requirement already satisfied: python-dotenv in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.3) (0.21.0)
Requirement already satisfied: gspread_dataframe in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.3) (3.3.1)
Requirement already satisfied: bs4 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.3) (0.0.2)
Requirement already satisfied: tenacity in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.3) (8.2.3)
Requirement already satisfied: langchain in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.3) (0.1.16)
Requirement already satisfied: langchain-openai in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.3) (0.1.3)
Requirement already satisfied: google-api-python-client in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.3) (2.127.0)
Requirement already satisfied: langchain-chroma in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.3) (0.1.0)
Requirement already satisfied: tavily-python in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.3) (0.3.3)
Requirement already satisfied: selenium in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from university-info-generator==0.0.3) (4.21.0)
Requirement already satisfied: beautifulsoup4 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from bs4->university-info-generator==0.0.3) (4.11.1)
Requirement already satisfied: httplib2<1.dev0,>=0.19.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-python-client->university-info-generator==0.0.3) (0.22.0)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-python-client->university-info-generator==0.0.3) (2.27.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-python-client->university-info-generator==0.0.3) (0.2.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-python-client->university-info-generator==0.0.3) (2.18.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-python-client->university-info-generator==0.0.3) (4.1.1)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from gspread->university-info-generator==0.0.3) (1.2.0)
Requirement already satisfied: StrEnum==0.4.15 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from gspread->university-info-generator==0.0.3) (0.4.15)
Requirement already satisfied: six>=1.12.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from gspread_dataframe->university-info-generator==0.0.3) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from pandas->university-info-generator==0.0.3) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from pandas->university-info-generator==0.0.3) (2022.7)
Requirement already satisfied: tzdata>=2022.7 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from pandas->university-info-generator==0.0.3) (2024.1)
Requirement already satisfied: PyYAML>=5.3 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.3) (6.0)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.3) (2.0.29)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.3) (3.8.3)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.3) (4.0.2)
Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.3) (0.6.4)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.3) (1.33)
Requirement already satisfied: langchain-community<0.1,>=0.0.32 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.3) (0.0.36)
Requirement already satisfied: langchain-core<0.2.0,>=0.1.42 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.3) (0.1.48)
Requirement already satisfied: langchain-text-splitters<0.1,>=0.0.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.3) (0.0.1)
Requirement already satisfied: langsmith<0.2.0,>=0.1.17 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.3) (0.1.50)
Requirement already satisfied: pydantic<3,>=1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.3) (1.10.11)
Requirement already satisfied: requests<3,>=2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain->university-info-generator==0.0.3) (2.28.1)
Requirement already satisfied: chromadb<0.5.0,>=0.4.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain-chroma->university-info-generator==0.0.3) (0.4.24)
Requirement already satisfied: fastapi<1,>=0.95.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain-chroma->university-info-generator==0.0.3) (0.110.2)
Requirement already satisfied: tiktoken<1,>=0.5.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain-openai->university-info-generator==0.0.3) (0.6.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from openai->university-info-generator==0.0.3) (3.5.0)
Requirement already satisfied: distro<2,>=1.7.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from openai->university-info-generator==0.0.3) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from openai->university-info-generator==0.0.3) (0.27.0)
Requirement already satisfied: sniffio in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from openai->university-info-generator==0.0.3) (1.2.0)
Requirement already satisfied: tqdm>4 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from openai->university-info-generator==0.0.3) (4.66.2)
Requirement already satisfied: typing-extensions<5,>=4.7 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from openai->university-info-generator==0.0.3) (4.11.0)
Requirement already satisfied: pyasn1>=0.1.7 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from oauth2client->university-info-generator==0.0.3) (0.4.8)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from oauth2client->university-info-generator==0.0.3) (0.2.8)
Requirement already satisfied: rsa>=3.1.4 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from oauth2client->university-info-generator==0.0.3) (4.9)
Requirement already satisfied: urllib3<3,>=1.26 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from urllib3[socks]<3,>=1.26->selenium->university-info-generator==0.0.3) (1.26.14)
Requirement already satisfied: trio~=0.17 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from selenium->university-info-generator==0.0.3) (0.22.2)
Requirement already satisfied: trio-websocket~=0.9 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from selenium->university-info-generator==0.0.3) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from selenium->university-info-generator==0.0.3) (2023.7.22)
Requirement already satisfied: attrs>=17.3.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->university-info-generator==0.0.3) (22.1.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->university-info-generator==0.0.3) (2.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->university-info-generator==0.0.3) (6.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->university-info-generator==0.0.3) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->university-info-generator==0.0.3) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->university-info-generator==0.0.3) (1.2.0)
Requirement already satisfied: idna>=2.8 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from anyio<5,>=3.5.0->openai->university-info-generator==0.0.3) (3.4)
Requirement already satisfied: build>=1.0.3 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (1.2.1)
Requirement already satisfied: chroma-hnswlib==0.7.3 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (0.7.3)
Requirement already satisfied: uvicorn>=0.18.3 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from uvicorn[standard]>=0.18.3->chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (0.29.0)
Requirement already satisfied: posthog>=2.4.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (3.5.0)
Requirement already satisfied: pulsar-client>=3.1.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (3.5.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (1.17.3)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (1.24.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (1.24.0)
Requirement already satisfied: opentelemetry-instrumentation-fastapi>=0.41b0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (0.45b0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (1.24.0)
Requirement already satisfied: tokenizers>=0.13.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (0.19.1)
Requirement already satisfied: pypika>=0.48.9 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (0.48.9)
Requirement already satisfied: overrides>=7.3.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (7.7.0)
Requirement already satisfied: importlib-resources in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (6.4.0)
Requirement already satisfied: grpcio>=1.58.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (1.62.2)
Requirement already satisfied: bcrypt>=4.0.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (4.1.2)
Requirement already satisfied: typer>=0.9.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (0.12.3)
Requirement already satisfied: kubernetes>=28.1.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (29.0.0)
Requirement already satisfied: mmh3>=4.0.1 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (4.1.0)
Requirement already satisfied: orjson>=3.9.12 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (3.10.1)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain->university-info-generator==0.0.3) (3.21.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain->university-info-generator==0.0.3) (0.8.0)
Requirement already satisfied: starlette<0.38.0,>=0.37.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from fastapi<1,>=0.95.2->langchain-chroma->university-info-generator==0.0.3) (0.37.2)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client->university-info-generator==0.0.3) (1.63.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client->university-info-generator==0.0.3) (4.21.12)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client->university-info-generator==0.0.3) (1.23.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client->university-info-generator==0.0.3) (5.3.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from google-auth-oauthlib>=0.4.1->gspread->university-info-generator==0.0.3) (1.3.1)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from httplib2<1.dev0,>=0.19.0->google-api-python-client->university-info-generator==0.0.3) (3.0.9)
Requirement already satisfied: httpcore==1.* in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from httpx<1,>=0.23.0->openai->university-info-generator==0.0.3) (1.0.4)
Requirement already satisfied: h11<0.15,>=0.13 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai->university-info-generator==0.0.3) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from jsonpatch<2.0,>=1.33->langchain->university-info-generator==0.0.3) (2.4)
Requirement already satisfied: packaging<24.0,>=23.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from langchain-core<0.2.0,>=0.1.42->langchain->university-info-generator==0.0.3) (23.2)
Requirement already satisfied: greenlet!=0.4.17 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from SQLAlchemy<3,>=1.4->langchain->university-info-generator==0.0.3) (3.0.3)
Requirement already satisfied: regex>=2022.1.18 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from tiktoken<1,>=0.5.2->langchain-openai->university-info-generator==0.0.3) (2022.7.9)
Requirement already satisfied: sortedcontainers in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from trio~=0.17->selenium->university-info-generator==0.0.3) (2.4.0)
Requirement already satisfied: outcome in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from trio~=0.17->selenium->university-info-generator==0.0.3) (1.2.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from trio~=0.17->selenium->university-info-generator==0.0.3) (1.1.3)
Requirement already satisfied: wsproto>=0.14 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from trio-websocket~=0.9->selenium->university-info-generator==0.0.3) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from urllib3[socks]<3,>=1.26->selenium->university-info-generator==0.0.3) (1.7.1)
Requirement already satisfied: soupsieve>1.2 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from beautifulsoup4->bs4->university-info-generator==0.0.3) (2.3.2.post1)
Requirement already satisfied: pyproject_hooks in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from build>=1.0.3->chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (1.0.0)
Requirement already satisfied: importlib-metadata>=4.6 in /home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages (from build>=1.0.3->chromadb<0.5.0,>=0.4.0->langchain-chroma->university-info-generator==0.0.3) (7.0.0)

In [2]:
import os
import sys
from pprint import pprint

#'/home/ivan/Uforse/university_crawl/fetch_logic'
current_path = os.path.abspath('./')

#'/home/ivan/Uforse/university_crawl'
parent_path = os.path.dirname(current_path)
sys.path.append(parent_path)
import sys
print(sys.executable)
sys.path.append('/home/ivan/Uforse/university_crawl')

/home/ivan/anaconda3/envs/gpu/bin/python

# Import

In [3]:
import pandas as pd
from pprint import pprint
from typing import Dict
from tqdm import tqdm
from collections import defaultdict
import numpy as np
import concurrent.futures

from university_info_generator import config
from university_info_generator import UniversityInfoGenerator
from university_info_generator import UniversityProgramScraper
from university_info_generator import Program

# Logic

In [4]:
scraper = UniversityProgramScraper()
canada_df = pd.read_csv(f"{scraper.data_repo_path}/canada_dataset/all_universities_canada.csv")
qs_df = pd.read_csv(f"{scraper.data_repo_path}/qs_ranking_2024.csv")

## canada

In [5]:
matched_df = UniversityProgramScraper.join_df(canada_df, qs_df)

In [6]:
scraper = UniversityProgramScraper(need_selenium = False)

In [7]:
canada_info_df = pd.read_csv(f"{scraper.data_repo_path}/canada_dataset/canada_info.csv", index_col="id_")

## scarp functions

In [8]:
def scrape_program_data(link, university_name, qs_general_program, key_set):
    program = Program()
    for key in key_set:
        program.update({key: ""})
    program.update({"university_name": university_name, "qs_program_link": link, "qs_general_program": qs_general_program})
    program = UniversityProgramScraper.extract_program_by_link(link, program=program)
    return program.to_dict_en()

def fetch_from_program_lst(program_lst: Dict[str, Dict[str, Dict[str, str]]], university_name: str):
    result_dict = {}
    key_set = Program.valid_keys
    key_set.difference_update(["program_id"])

    total_programs = sum(len(program_lst[study_degree][qs_general_program]) for study_degree in program_lst for qs_general_program in program_lst[study_degree])

    with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
        future_to_program = {}

        for study_degree in program_lst:
            for qs_general_program in program_lst[study_degree]:
                for program_name in program_lst[study_degree][qs_general_program]:
                    link = program_lst[study_degree][qs_general_program][program_name]
                    future = executor.submit(scrape_program_data, link, university_name, qs_general_program, key_set)
                    future_to_program[future] = f"{study_degree} - {program_name}"
        with tqdm(total=total_programs, desc="Scraping Programs") as pbar:
            for future in concurrent.futures.as_completed(future_to_program):
                program_name = future_to_program[future]
                try:
                    result_dict[program_name] = future.result()
                except Exception as exc:
                    print(f'Program {program_name} generated an exception: {exc}')
                    raise
                pbar.update(1)
    return result_dict

# scrap on one

In [9]:
# uwaterloo_program_lst = scraper.get_program_link_lst(link = "https://www.topuniversities.com/universities/university-waterloo")
# pprint(uwaterloo_program_lst)

In [10]:
import csv


def save_program_dict(program_dict, uni_name: str, partial_path: str):
    with open(
        f"/home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/\
{partial_path}/program_dict/{'_'.join(uni_name.lower().split())}_program_dict.csv",
        "w",
        newline="",
    ) as csvfile:
        fieldnames = ["degree_type", "qs_general_program", "program_name", "qs_program_link"]
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        writer.writeheader()
        for level, categories in program_dict.items():
            for category, programs in categories.items():
                for program, url in programs.items():
                    writer.writerow({"degree_type": level, "qs_general_program": category, "program_name": program, "qs_program_link": url})

In [11]:
# save_program_dict(uwaterloo_program_lst, "University of Waterloo", "canada")

In [12]:
# result = fetch_from_program_lst(uwaterloo_program_lst, "Universty of Waterloo")
# df = pd.DataFrame(result).T
# df.to_csv("/home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada/uwaterloo_programs.csv", encoding="utf-8")

## Scrap on all

In [13]:
scraper = UniversityProgramScraper()
canada_df = pd.read_csv(f"{scraper.data_repo_path}/canada_dataset/all_universities_canada.csv")
qs_df = pd.read_csv(f"{scraper.data_repo_path}/qs_ranking_2024.csv")
matched_df = UniversityProgramScraper.join_df(canada_df, qs_df)
matched_df.head()

,id_,rank,qs_uni_link
university_name,,,
University of Toronto,49,21,https://www.topuniversities.com/universities/u...
University of Calgary,92,182,https://www.topuniversities.com/universities/u...
Memorial University of Newfoundland,1,641-650,https://www.topuniversities.com/universities/m...
Dalhousie University,7,298,https://www.topuniversities.com/universities/d...
University of New Brunswick,15,711-720,https://www.topuniversities.com/universities/u...

In [14]:
matched_df.index

Index(['University of Toronto', 'University of Calgary',
       'Memorial University of Newfoundland', 'Dalhousie University',
       'University of New Brunswick', 'McGill University',
       'Université de Montréal', 'Concordia University', 'Carleton University',
       'University of Ottawa', 'Victoria University', 'Western University',
       'University of Windsor', 'York University', 'University of Manitoba',
       'University of Regina', 'University of Saskatchewan',
       'University of Alberta', 'University of Northern British Columbia',
       'Vancouver Island University', 'Brock University',
       'University of Waterloo', 'Simon Fraser University'],
      dtype='object', name='university_name')

In [15]:
matched_df.head()

,id_,rank,qs_uni_link
university_name,,,
University of Toronto,49,21,https://www.topuniversities.com/universities/u...
University of Calgary,92,182,https://www.topuniversities.com/universities/u...
Memorial University of Newfoundland,1,641-650,https://www.topuniversities.com/universities/m...
Dalhousie University,7,298,https://www.topuniversities.com/universities/d...
University of New Brunswick,15,711-720,https://www.topuniversities.com/universities/u...

In [16]:
# result = fetch_from_program_lst(uwaterloo_program_lst, "Universty of Waterloo")
from tenacity import retry, wait_random_exponential, retry_if_exception_type, stop_any, stop_after_attempt, stop_after_delay
from requests import HTTPError
# from selenium.common.exceptions import ClientError
import time

def scrap_all_from_df(df: pd.DataFrame, repo_path = "canada"):
    def process(uni_name, link, retries=3, delay=15):
        for attempt in range(retries):
            try:
                program_dct = UniversityProgramScraper.get_program_link_lst(link)
                # time.sleep(20)
                # fetched_result = fetch_from_program_lst(program_lst, university_name)
                save_program_dict(program_dct, uni_name, repo_path)
                # return fetched_result
            except (Exception) as exc:
                print(f"attempt:{attempt} HTTP error occurred: {exc}. Retrying in {delay} seconds...")
                time.sleep(delay)
                delay *= 2  # Exponential backoff
        return None
    for i, row in df.iterrows():
        university_name = i
        qs_uni_link = row["qs_uni_link"]
        print(i, qs_uni_link)
        result = process(i, qs_uni_link)
        if not result:
            continue
        df = pd.DataFrame(result).T
        df.to_csv(f"/home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/{repo_path}/{'_'.join(university_name.lower().split())}_program.csv", encoding="utf-8")
        break

## Program dict

In [17]:
# Program.set_program_id(0)
# scrap_all_from_df(matched_df)

In [18]:
finished_lst = [
    "concordia_university",
    "dalhousie_university",
    "mcgill_university",
    "memorial_university_of_newfoundland",
    "university_of_toronto",
    "university_of_windsor",
    "vancouver_island_university",
    "victoria_university",
    "york_university",
    "the_new_school",
    "wayne_state_university",
    "carnegie_mellon_university",
    "west_virginia_university",
    "university_of_washington",
    "georgia_state_university",
    "michigan_state_university",
    "northwestern_university",
    "vanderbilt_university",
    "yale_university",
    "drexel_university",
    "johns_hopkins_university",
    "central_michigan_university",
    "ohio_university",
    "temple_university",
    "university_of_san_diego",
    "university_of_cincinnati",
    "oregon_state_university",
    "university_of_miami",
    "university_of_north_texas",
    "southern_methodist_university",
    "kansas_state_university",
    "illinois_institute_of_technology",
    "university_of_connecticut",
    "university_of_chicago",
    "colorado_school_of_mines",
    "worcester_polytechnic_institute",
    "university_of_southern_california",
    "university_of_notre_dame",
    "university_of_oklahoma",
    "columbia_university",
    "rice_university",
    "clark_university",
    "kent_state_university",
    "boston_university",
    "university_of_pennsylvania",
    "rensselaer_polytechnic_institute",
    "saint_louis_university",
    "university_of_maryland,_baltimore_county",
    "indiana_state_university",
    "colorado_state_university",
    "university_of_south_carolina",
    "nova_southeastern_university",
    "university_of_mississippi",
    "university_of_san_francisco",
    "university_of_wyoming",
]

In [19]:
import os
import glob


def get_university_name(file_name):
    return file_name.replace("_program_dict.csv", "").replace("_", " ").title()


def fetch_from_program_lst_csv_render(rows, university_name: str, driver):
    result_dict = {}
    key_set = Program.valid_keys
    key_set.difference_update(["program_id"])

    total_programs = len(rows)

    with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
        future_to_program = {}

        for row in rows:
            degree_type, qs_general_program, program_name, qs_program_link = row
            future = executor.submit(
                scrape_program_data, qs_program_link, university_name, qs_general_program, key_set, driver
            )
            future_to_program[future] = f"{degree_type} - {program_name}"
        with tqdm(total=total_programs, desc="Scraping each program") as pbar:
            for future in concurrent.futures.as_completed(future_to_program):
                program_name = future_to_program[future]
                try:
                    result_dict[program_name] = future.result()
                except Exception as exc:
                    print(f"Program {program_name} generated an exception: {exc}")
                    raise
                pbar.update(1)
    return result_dict


def scrape_program_data(link, university_name, qs_general_program, key_set, driver):
    program = Program()
    for key in key_set:
        program.update({key: ""})
    program.update(
        {"university_name": university_name, "qs_program_link": link, "qs_general_program": qs_general_program}
    )
    program = UniversityProgramScraper.extract_program_by_link(link, program=program, driver_prm=driver)
    return program.to_dict_en()


def fetch_programs_from_repo(partial_path: str, driver):
    # Define the path to the repository
    repo_path = f"/home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/{partial_path}"
    full_path = f"{repo_path}/program_dict"

    # Change to the repository directory
    os.chdir(full_path)

    # Use glob to find all CSV files in the repository
    csv_files = glob.glob("*.csv")

    # Iterate through each CSV file
    for csv_file in csv_files:
        university_name = get_university_name(csv_file)
        if (uni_name := '_'.join(university_name.lower().split())) in finished_lst or os.path.isfile(os.path.join(repo_path, f"{uni_name}_program_dict.csv")):
            print(f"skip {uni_name}")
            continue
        print(f"Processing file: {csv_file}")
        # You can add more processing logic here, e.g., reading the CSV file
        with open(csv_file, "r", encoding="utf-8") as file:
            reader = csv.reader(file)
            rows = list(reader)
            result = fetch_from_program_lst_csv_render(rows[1:], university_name, driver)
            if not result:
                continue
            df = pd.DataFrame(result).T
            df.to_csv(
                f"/home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/{partial_path}/{'_'.join(university_name.lower().split())}_program.csv",
                encoding="utf-8",
            )
            finished_lst.append('_'.join(university_name.lower().split()))
            # Iterate through each line in the CSV file
            # row_number = 0
            # for row in reader:
            #     print(row)  # Print the content of the line or process it as needed
            #     row_number += 1
            #     if row_number >= 2:
            #         degree_type, qs_general_program, program_name, qs_program_link = row
            #         print(university_name, qs_uni_link)
            #         result = process()
            # print(content)  # Print the content of the CSV file or process it as needed

In [20]:
# print(result_dict)

### fetch canada repo

In [21]:
# from selenium.webdriver.chrome.service import Service
# from selenium import webdriver
# from selenium.common.exceptions import WebDriverException
# try:
#     service = Service("/usr/bin/chromedriver/chromedriver")
#     driver = webdriver.Chrome(service=service)
#     fetch_programs_from_repo("canada", driver=driver)
# except WebDriverException as exc:
#     print(f"Error:   {exc}")
# finally:
#     driver.close()

### usa

In [22]:
from selenium.webdriver.chrome.service import Service
from selenium import webdriver
from selenium.common.exceptions import WebDriverException
try:
    service = Service("/usr/bin/chromedriver/chromedriver")
    driver = webdriver.Chrome(service=service)
    fetch_programs_from_repo("usa", driver=driver)
except WebDriverException as exc:
    print(f"Error:   {exc}")
finally:
    driver.close()

skip the_new_school
skip wayne_state_university
skip carnegie_mellon_university
Processing file: university_of_new_mexico_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

Processing file: university_of_california,_irvine_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

skip west_virginia_university
skip university_of_washington
skip georgia_state_university
skip michigan_state_university
skip northwestern_university
skip vanderbilt_university
skip yale_university
skip drexel_university
Processing file: north_carolina_state_university_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

skip johns_hopkins_university
Processing file: university_of_new_hampshire_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

Processing file: texas_tech_university_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

Processing file: university_of_california,_riverside_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

Processing file: mississippi_state_university_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

skip central_michigan_university
skip ohio_university
skip temple_university
skip university_of_san_diego
skip university_of_cincinnati
Processing file: university_of_rhode_island_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

skip oregon_state_university
skip university_of_miami
skip university_of_north_texas
skip southern_methodist_university
skip kansas_state_university
skip illinois_institute_of_technology
skip university_of_connecticut
skip university_of_chicago
skip colorado_school_of_mines
skip worcester_polytechnic_institute
Processing file: university_of_south_florida_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

skip university_of_southern_california
skip university_of_notre_dame
skip university_of_oklahoma
skip columbia_university
skip rice_university
skip clark_university
skip kent_state_university
Processing file: university_of_california,_davis_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

skip boston_university
skip university_of_pennsylvania
Processing file: lebanese_american_university_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

skip rensselaer_polytechnic_institute
skip saint_louis_university
skip university_of_maryland,_baltimore_county
skip york_university
skip indiana_state_university
Processing file: brigham_young_university_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

skip colorado_state_university
skip university_of_south_carolina
skip nova_southeastern_university
skip university_of_mississippi
skip university_of_san_francisco
skip university_of_wyoming
Processing file: northeastern_university_program_dict.csv

Scraping each program: 100%|██████████| 184/184 [07:32<00:00,  2.46s/it]

Processing file: university_of_kentucky_program_dict.csv

Scraping each program: 100%|██████████| 257/257 [11:23<00:00,  2.66s/it]

Processing file: university_of_texas_at_san_antonio_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

Processing file: university_of_virginia_program_dict.csv

Scraping each program: 100%|██████████| 13/13 [00:32<00:00,  2.54s/it]

Processing file: emory_university_program_dict.csv

Scraping each program: 100%|██████████| 156/156 [07:05<00:00,  2.72s/it]

Processing file: university_of_colorado_boulder_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

Processing file: university_of_denver_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

Processing file: yeshiva_university_program_dict.csv

Scraping each program: 100%|██████████| 1/1 [00:03<00:00,  3.10s/it]

Processing file: university_of_central_oklahoma_program_dict.csv

Scraping each program: 0it [00:00, ?it/s]

Processing file: duke_university_program_dict.csv

Scraping each program:   0%|          | 0/315 [00:08<?, ?it/s]

In [ ]:
print(finished_lst)

['concordia_university', 'dalhousie_university', 'mcgill_university', 'memorial_university_of_newfoundland', 'university_of_toronto', 'university_of_windsor', 'vancouver_island_university', 'victoria_university', 'york_university', 'the_new_school', 'wayne_state_university', 'carnegie_mellon_university', 'west_virginia_university', 'university_of_washington', 'georgia_state_university', 'michigan_state_university', 'northwestern_university', 'vanderbilt_university', 'yale_university', 'drexel_university', 'johns_hopkins_university', 'central_michigan_university', 'ohio_university', 'temple_university', 'university_of_san_diego', 'university_of_cincinnati', 'oregon_state_university', 'university_of_miami', 'university_of_north_texas', 'southern_methodist_university', 'kansas_state_university', 'illinois_institute_of_technology', 'university_of_connecticut', 'university_of_chicago', 'colorado_school_of_mines', 'worcester_polytechnic_institute', 'university_of_southern_california', 'university_of_notre_dame', 'university_of_oklahoma', 'columbia_university', 'rice_university', 'clark_university', 'kent_state_university', 'boston_university', 'university_of_pennsylvania', 'rensselaer_polytechnic_institute', 'saint_louis_university', 'university_of_maryland,_baltimore_county', 'indiana_state_university', 'colorado_state_university', 'university_of_south_carolina', 'nova_southeastern_university', 'university_of_mississippi', 'university_of_san_francisco', 'university_of_wyoming']

In [ ]:
break

In [ ]:
from selenium.webdriver.chrome.service import Service
from selenium import webdriver
from selenium.common.exceptions import WebDriverException
try:
    service = Service("/usr/bin/chromedriver/chromedriver")
    driver = webdriver.Chrome(service=service)
    fetch_programs_from_repo("canada", driver=driver)
except WebDriverException as exc:
    print(f"Error:   {exc}")
finally:
    driver.close()

SyntaxError: 'break' outside loop (668683560.py, line 1)

In [ ]:
def combine_csv_to_excel(csv_folder_path, output_excel_path):
    # Create a new Excel writer object
    with pd.ExcelWriter(output_excel_path, engine='openpyxl') as writer:
        # Iterate through all CSV files in the specified folder
        for filename in os.listdir(csv_folder_path):
            if filename.endswith(".csv"):
                file_path = os.path.join(csv_folder_path, filename)
                # Read the CSV file into a DataFrame
                df = pd.read_csv(file_path)
                # Write the DataFrame to a sheet in the Excel file
                sheet_name = os.path.splitext(filename)[0]  # Use the CSV file name (without extension) as the sheet name
                df.to_excel(writer, sheet_name=sheet_name, index=False)
                print(f"Added {filename} to {output_excel_path} as sheet {sheet_name}")

In [ ]:

csv_folder_path = "/home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada/"
output_excel_path = "/home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx"
combine_csv_to_excel(csv_folder_path, output_excel_path)

Added university_of_toronto_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet university_of_toronto_program
Added brock_university_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet brock_university_program
Added university_of_northern_british_columbia_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet university_of_northern_british_columbia_program
Added mcgill_university_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet mcgill_university_program
Added university_of_saskatchewan_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet university_of_saskatchewan_program
Added university_of_windsor_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet university_of_windsor_program
Added university_of_regina_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet university_of_regina_program
Added simon_fraser_university_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet simon_fraser_university_program
Added university_of_calgary_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet university_of_calgary_program
Added concordia_university_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet concordia_university_program

/home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages/openpyxl/workbook/child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")
/home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages/openpyxl/workbook/child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")

Added carleton_university_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet carleton_university_program
Added university_of_ottawa_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet university_of_ottawa_program
Added university_of_manitoba_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet university_of_manitoba_program
Added university_of_new_brunswick_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet university_of_new_brunswick_program
Added university_of_waterloo_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet university_of_waterloo_program
Added victoria_university_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet victoria_university_program

/home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages/openpyxl/workbook/child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")

Added université_de_montréal_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet université_de_montréal_program
Added western_university_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet western_university_program
Added memorial_university_of_newfoundland_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet memorial_university_of_newfoundland_program
Added university_of_alberta_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet university_of_alberta_program
Added dalhousie_university_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet dalhousie_university_program
Added vancouver_island_university_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet vancouver_island_university_program

/home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages/openpyxl/workbook/child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")
/home/ivan/anaconda3/envs/gpu/lib/python3.9/site-packages/openpyxl/workbook/child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")

Added york_university_program.csv to /home/ivan/Uforse/university_crawl/university_info_generator/fetch_logic/fetch_data/programs/canada_university_programs_combined.xlsx as sheet york_university_program

In [ ]:
# import requests
# from requests.exceptions import HTTPError
# from bs4 import BeautifulSoup
# from bs4.element import Tag, ResultSet, PageElement

# link = "https://www.topuniversities.com/universities/university-toronto"
# base_url = "https://www.topuniversities.com"

# program_dict: Dict[str, Dict[str, Dict[str, str]]] = {}
# try:
#     # base_url = "https://www.topuniversities.com"
#     response:requests.Response = requests.get(link)
#     response.raise_for_status()
#     page_content = response.content
#     page_soup = BeautifulSoup(page_content, "html.parser")
#     # Bachelor/Master
#     dpt_lst = page_soup.find(name="ul", attrs={"id": "aptabs"}).find_all(name="h3")
#     for dpt in dpt_lst:
#         if not dpt.span:
#             program_dict[dpt.text.lower().strip()] = {}
#         else:
#             program_dict[dpt.span.text.lower().strip()] = {}
#     panel_group_by_dpt = page_soup.find_all(name="div", attrs={"class": "panel-group"})
#     print( len(panel_group_by_dpt), len(program_dict))
#     for each_group, dpt in zip(panel_group_by_dpt, program_dict):
#         # Arts and humanities
#         soup = BeautifulSoup(str(each_group), "html.parser")
#         subject_areas: ResultSet = soup.find_all(name="div", attrs={"class": "item"})
#         subject_area: Tag
#         for subject_area in subject_areas:
#             department_name = subject_area.find(
#                 name="span", attrs={"class": "pgmname"}, recursive=True
#             ).text
#             program_dict[dpt].update({department_name: {}})
#             programs = subject_area.find(name="div", attrs={"class": "item-body"}).find_all(
#                 name="div", attrs={"class": "views-row"}
#             )
#             program_body: Tag
#             # Architectural Engineering
#             for program_body in programs:
#                 program_name: str = program_body.find(name="h4").text
#                 program_link = program_body.find(name="a", attrs={"id": "view_details"}).get("href")
#                 program_dict[dpt][department_name].update(
#                     {program_name.strip(): base_url + program_link}
#                 )
# except HTTPError as http_err:
#     print(f"HTTP error occurred: {http_err}")
# # return program_dict

In [ ]:
# pprint(program_dict)

In [ ]:
scraper.quit_driver()

## usa

In [ ]:
us_df = pd.read_csv(f"{scraper.data_repo_path}/usa_dataset/all_universities_usa.csv")
matched_usa_df = UniversityProgramScraper.join_df(us_df, qs_df, save_path=f"{config.PROJECT_HOME}/university_info_generator/data/usa_dataset/qs_usa_uni_matched.csv")

In [ ]:
# Program.set_program_id(0)
# scrap_all_from_df(matched_usa_df, "usa")

In [ ]:
# Program.set_program_id(0)
# scrap_all_from_df(matched_usa_df, repo_path="usa")